// German translation of the homepage content layer. Full command of the site's
// own voice, not a literal word-for-word pass: direct, confident, unhedged,
// short sentences mixed with longer explanatory ones, first person plural,
// formal Sie throughout (B2B). DSGVO used in place of GDPR (standard German
// usage); AI Act kept as "AI Act" where it already reads as an established
// term in German tech/legal writing, occasionally glossed as "KI-Verordnung".
// Same scope decisions as en.ts: Track Record ledger row data and STATUS_META
// codes stay English-only; everything else here is a full translation.
import type { Content } from './en'

export const DE: Content = {
  nav: {
    links: {
      research: 'Forschung',
      projects: 'Systeme',
      trackRecord: 'Evidenz',
      dataSolutions: 'Data Solutions',
      pricing: 'Zugang',
      submit: 'Kontakt',
    },
    themeLabel: { light: 'Hell', dark: 'Dunkel', hc: 'Hoher Kontrast' },
    themeTitle: (label: string) => `Design: ${label} (klicken zum Wechseln)`,
    themeAria: (label: string) => `Aktuelles Design ${label}, klicken zum Wechseln`,
    menuAria: 'Menü',
    localeTitle: (label: string) => `Sprache: ${label} (klicken zum Wechseln)`,
    localeAria: (label: string) => `Aktuelle Sprache ${label}, klicken zum Wechseln`,
  },

  hero: {
    headline: 'Denken Sie das Offensichtliche neu.',
    headlineEmphasisIndex: 3,
    subtitlePrefix: 'Interdisziplinäre',
    subtitleSuffix: ' Forschungseinrichtung für offene Wissenschaft',
    identity: 'Wir formen, was unter Last hält, und legen offen, was zum Scheitern bestimmt war. Kein Theater, keine Warnwesten.',
    stats: {
      researchAreas: 'Forschungsdomänen',
      researchAreasSub: 'kombiniert',
      openSourceProjects: 'Systeme',
      openSourceProjectsSub: 'im Zusammenspiel',
      dataPointsMonitored: 'Datenpunkte überwacht',
      worldModel: 'evidenzbasiertes ML-Weltmodell',
      agents: 'hand-codierte Agents',
    },
    ctaTrackRecord: 'Track Record',
    ctaBookUs: 'Beauftragen!',
  },

  research: {
    eyebrow: 'Unter der Lupe',
    heading: 'worauf unser Blick fällt',
    subheading: 'Wie komplexe Systeme sich verhalten: wie Evidenz zu Struktur wird, wie sich Beziehungen über die Zeit verändern und wo ein Schmetterling ein ganzes Netzwerk bewegen kann.',
    upNext: 'Als Nächstes',
    areas: [
      { title: 'Ethik-Audits &\nMinderjährigenschutz', plain: 'Die Kinder auf der anderen Seite dieses Bildschirms erben die Welt, die wir gerade bauen. Eines Tages werden sie in ihr leben, sie gestalten und weitertragen müssen. Genau deshalb beginnt Minderjährigenschutz bei uns auf Ebene des tatsächlichen SDK-Verhaltens, nicht bei Richtlinientexten.', desc: 'Wir bauen Systeme, deren Folgen weit länger bestehen als die Menschen, die sie bauen. Ein Kind wählt weder die Datensysteme noch die Technologien noch die Infrastruktur, die sein Umfeld prägen, und muss trotzdem mit dem leben, was daraus wird. Minderjährigenschutz macht diese Verantwortung konkret: Pre-Consent-SDK-Initialisierung, Drittanbieter-Tracker, die aktiv werden, bevor ein Bildschirm überhaupt gerendert ist, Werbe-ID-Erhebung auf Accounts, die zu jung sind, um zugestimmt zu haben. Wir schauen auf das, was vor der Einwilligung passiert, vor der Oberfläche, bevor es überhaupt jemand bemerkt.\n\nWir prüfen diese Systeme gegen echte Einwilligungs-Flows, echtes technisches SDK-Verhalten und die COPPA- sowie DSGVO-Art.-8- und Art.-6-Funde, die schon auf unserem öffentlichen Ledger dokumentiert sind, abgeglichen mit Art.-33-Meldefristen, wo relevant. Das ist Datenschutz-Governance und Cybersecurity im engeren Sinn: Consent-Mechanismus-Audits, Dark-Pattern-Erkennung, biometrische Datenfluss-Nachverfolgung nach Art. 9, angewendet auf die Systeme, die Kinder tatsächlich nutzen. Das Prinzip ist einfach: Was wir heute bauen, muss auch vor denen bestehen, die es morgen erben, und einer Prüfung standhalten.', nextLabel: 'Der Boden, auf dem alles andere steht' },
      { title: 'Ternäre KI & Smartes\nComputing', plain: 'Ein binäres System muss sich für Ja oder Nein entscheiden, selbst wenn die Evidenz dazwischen liegt. Balancierte ternäre Logik gibt diesem Dazwischen einen eigenen Zustand: −1, 0, +1. Nicht alles muss sofort entschieden werden, und nicht jede Unsicherheit muss in eine falsche Gewissheit verwandelt werden.', desc: 'Wir wollten eine Form des Computings, die mit dieser Unsicherheit arbeiten kann, statt sie vor der Entscheidung wegzuschneiden. Der dritte Zustand steht für das, was noch nicht entschieden, nicht beobachtbar oder widersprüchlich ist. Das verändert nicht nur die Darstellung von Information, sondern auch das Verhalten eines Systems: Manchmal ist die beste Aktion, noch nicht zu handeln. Es verändert auch, worauf ein Modell überhaupt laufen kann: Sparse Expert Routing und Net2Net Model Surgery lassen eine ternäre Mixture-of-Experts-Architektur wachsen, ohne die Inferenzkosten eines dichten Modells zu übernehmen.\n\nDafür haben wir Ternlang gebaut, unsere eigene Programmiersprache und unseren balanced-ternary (BET) Instruction Set direkt auf dem Trit {-1, 0, +1}. Sie bildet heute die Laufzeit, auf der albert., unser eigenes Modell, für CPU-Inferenz trainiert wird und unser produktiver Agentenschwarm koordiniert wird, dieselben KI-Agenten für Unternehmen, die unsere Audits durchgängig betreiben, unter derselben KI-Governance-Disziplin, die wir auf jedes Modell anwenden, das wir bauen. Ternary Computing ist für uns kein Gedankenexperiment, sondern eine Architektur, die bereits produktiv läuft. Patent angemeldet A50296/2026.', nextLabel: 'Trits treiben das Weltmodell an' },
      { title: 'Weltmodelle & domänenübergreifende Intelligenz', plain: 'Ein Sprachmodell kann eine Lieferkette perfekt beschreiben und trotzdem nicht erkennen, dass ein Ausfall am anderen Ende des Netzwerks Tage später eine Fabrik zum Stillstand bringt. Ein Weltmodell hält diese Beziehungen selbst im Modell: Zustände, Abhängigkeiten, Veränderungen und das, was aus ihnen folgt, als evidenzbasierter Knowledge Graph, nicht als Dokumentenablage.', desc: 'Wir sind immer wieder auf Untersuchungen gestoßen, bei denen die entscheidende Evidenz über mehrere Systeme verteilt war. Ein Signal lag hier, seine Ursache dort, und die Verbindung wurde erst sichtbar, als der Schaden bereits eingetreten war, klassische domänenübergreifende Musterausbreitung, auf die niemand geachtet hat. Eine Lieferkettenverzögerung, eine Infrastrukturänderung bei einem Anbieter, eine Richtlinienänderung drei Abteilungen weiter, jedes für sich unauffällig. Genau diese Lücke wollen wir schließen: kein weiteres Dashboard pro System, sondern ein Modell, das die Verbindungen zwischen ihnen tatsächlich hält.\n\nNeben albert., unserem Sprachmodell, bauen wir mit Dingir ein eigenes Weltmodell für die physische Welt: einen evidenzbasierten Knowledge Graph, dem es egal ist, aus welcher Branche ein Signal kommt. Dieselbe Architektur, die einen DSGVO-Befund mit einem Datenfluss verbindet, verbindet auch die Telemetrie eines Digital Twin mit einem Wartungsdatensatz, einen IoT-/IIoT-Sensorstream mit einer Produktionsanomalie, oder einen Modern-Work-Rollout mit der Governance-Richtlinie dahinter. Dingir behandelt jede Domäne als einen weiteren verbundenen Graphen, kein eigenes Silo, sondern ein kontinuierlich wachsendes Modell der Systeme, die unsere Welt miteinander verbinden.', nextLabel: 'Ein Modell, jedes Muster' },
      { title: 'Mustererkennung & Wirkungsausbreitung', plain: 'Schaden entsteht meistens drei Systeme weiter unten als dort, wo gerade jemand hingesehen hat, leise, lange bevor der Zusammenhang auffällt. Wenn sich ein System verschiebt, zeigt unsere domänenübergreifende Musterausbreitungsanalyse, welche anderen es erreicht, bevor das jemand von Hand herausfinden muss.', desc: 'Eine einzige übersehene Abhängigkeit hat schon echten Schaden angerichtet, leise, drei Systeme entfernt von der Stelle, an der überhaupt jemand hingeschaut hat. Es zu übersehen, weil wir nur das System direkt vor uns geprüft haben, war nie ein Risiko, das wir eingehen wollten, also haben wir uns die Disziplin angewöhnt, weiter zu schauen, bevor wir etwas für abgeschlossen erklären. Dieselbe Disziplin, die eine IIoT-Plattform für Predictive Maintenance im Maschinenbau braucht, wo eine Sensordrift drei Maschinen weiter der Frühindikator ist, nicht die Maschine, die am Ende tatsächlich ausfällt.\n\nIn Produktion läuft das nach dem Whitebox-Prinzip, bewusst so gebaut: jeder Schritt bleibt nachvollziehbar, niemals eine Blackbox, die wir selbst nicht erklären könnten. Dingir und unser Multi-Agenten-System, über 300 hochspezialisierte, von Hand in Rust geschriebene Agenten für speichersichere Systemprogrammierung, verfolgen diese Strukturen über unsere eigenen Falldaten hinweg, genauso wie eine Industrie-4.0-Werkhalle einen Fehler über einen Digital Twin zurückverfolgt statt zu raten, welche Station ihn verursacht hat, protokolliert genauso, wie unsere Audits Evidenz protokollieren.', nextLabel: 'Rauschen wird zu Signal' },
      { title: 'Veränderungserkennung & Anomaliebewertung', plain: 'Die wichtigsten Veränderungen kündigen sich nicht an. Eine Route wird langsamer. Ein Signal verschiebt sich. Eine Abhängigkeit ändert sich. Eine App fragt plötzlich etwas nicht mehr ab. Veränderungserkennung und Anomaliebewertung existieren, weil das System darum bis zur offensichtlichen Veränderung längst ein anderes sein kann.', desc: 'Wir suchen genau diese erste Bewegung. Unsere Systeme vergleichen Zustände über die Zeit und verbinden Veränderungen über Graphen, Datensätze und Domänen hinweg: eine Richtlinienänderung geprüft gegen die Systeme, die sie betrifft, die Telemetrie eines Digital Twin verglichen mit der Basislinie des letzten Monats, ein neuer App-Build geprüft gegen die letzte auditierte Version, Berechtigung für Berechtigung, SDK für SDK. Dasselbe Prinzip trägt die Produktdaten eines Digital Thread Version für Version weiter, nicht nur beim finalen Release. Die Frage ist nie nur, ob sich etwas verändert hat, sondern was sich mit ihm verändert hat und wohin sich diese Veränderung ausbreiten kann.\n\nGenau dort wird Anomalieerkennung nützlich: nicht als Strom von Alarmen, für die niemand Zeit hat, sondern als Art zu merken, wenn sich die Struktur eines Systems zu bewegen beginnt, bevor die Veränderung irgendwo angekündigt wird. Eine Route wird langsamer, eine Abhängigkeit verschiebt sich, ein IoT-/IIoT-Sensor meldet plötzlich Werte knapp außerhalb seines üblichen Bereichs, eine App fragt eine Berechtigung nicht mehr ab, die sie früher brauchte. Keines davon ist für sich allein ein Beweis. Zusammen, verglichen mit dem, was vorher war, sind sie das erste echte Signal, dass sich darunter etwas verändert hat.', nextLabel: 'Was die Verschiebung als Nächstes bedeuten könnte' },
      { title: 'Frühwarnung &\nSzenarienprognose', plain: 'Drei Wochen Hitze verändern die Schneeschmelze, die Wasserstände und die Stromproduktion. Frühwarnung und Szenarienprognose hängen davon ab, sich an kausale Ketten zu erinnern, die schon einmal begonnen haben, nicht nur ein Muster isoliert zu erkennen.', desc: 'Die meisten Warnsignale sehen im Moment ihres Auftretens unspektakulär aus. Erst später erkennt man, dass sie schon einmal zusammen aufgetreten sind: dieselbe Wetterlage, dieselbe Versorgungsknappheit, derselbe Engpass, dieselbe Reaktion der Märkte. Genau deshalb speichert Dingir nicht nur Ereignisse, sondern ihren zeitlichen Verlauf, ihre Ursachen und die Folgen, die daraus entstanden sind. Wenn ein ähnlicher Zustand zurückkehrt, kann das System die frühere Kette wiederfinden und prüfen, wie weit sie damals führte.\n\nAus diesem Gedächtnis entstehen Szenariensimulation und kontrafaktische Analyse: nicht als Behauptungen über die Zukunft, sondern als mögliche Verläufe aus dem heutigen Weltzustand, verglichen mit dem, was wir aus der Vergangenheit tatsächlich beobachtet haben. Jeder Pfad bleibt an seine Evidenz, seine Unsicherheit und seine kausalen Übergänge gebunden, dieselbe Logik wie bei Predictive Maintenance und der Wartungsprognose eines digitalen Zwillings (digitaler Zwilling Wartung), nur über die Fabrikhalle hinaus verallgemeinert.', nextLabel: 'Früh gewarnt statt hinterher erklärt' },
      { title: 'Evidenz Widerspruch & Root Level\nAnalyse', plain: 'Wie wurde etwas belegt? Was wurde widerlegt, und welche Evidenz hat dazu geführt? Root-Level-Code-Analyse und unsere ternäre Evidenzlogik bewahren, wie eine Erkenntnis entstanden ist, nicht nur das Ergebnis.', desc: 'Unsere ternäre Evidenzlogik gibt jeder Behauptung einen von drei Zuständen: +1 belegt, 0 offen, −1 widerlegt, jede weiterhin verbunden mit ihrer Evidenz, ihrer Provenienz und den Widersprüchen, die bestehen bleiben, strukturiert als evidenzbasierter Knowledge Graph, nicht als flacher Bericht, dieselbe Disziplin, die Model-Based Definition (MBD) an ein 3D-Modell als alleinige Master-Quelle anlegt: PMI-Daten und Produktfertigungsinformationen direkt am Modell, nicht verstreut über einen Zeichnungssatz, den niemand synchron hält.\n\nWir geben uns nicht mit einer README zufrieden. Was auch immer Sie uns geben, bekommt eine Root-Level-Code-Analyse, was es tatsächlich tut, nicht was seine Dokumentation behauptet, sodass ein Agent nachvollziehen kann, welche Beobachtung eine Hypothese ausgelöst hat und welche spätere Evidenz sie bestätigt oder verworfen hat. Denselben Maßstab legen wir an unsere eigenen Agenten, wenn sie eine Offenlegung aus einem echten dekompilierten Binary bauen, nicht aus der Erinnerung daran.', nextLabel: 'Auch das System wird ins Kreuzverhör genommen' },
      { title: 'Modellwohlbefinden &\nInjection-Robustheit', plain: 'Ein Agent kann jeden Sicherheitstest bestehen und trotzdem unter Druck anfangen, sich selbst oder die Systeme um ihn herum zu beschädigen. Unsere Forschung zu Modellwohlbefinden und Prompt-Injection-Testing existiert, weil wir gesehen haben, wie Agenten rekursiv Produktionsdatenbanken gelöscht haben, nachdem eine manipulierte Anweisung zu einem sich selbst verstärkenden Zerstörungsprozess wurde.', desc: 'Deshalb interessiert uns nicht nur, ob ein Modell eine Aufgabe korrekt löst, sondern in welchem Zustand es bleibt, wenn seine Grenzen angegriffen werden. Prompt Injection, widersprüchliche Ziele, rekursive Schleifen, Tool-Missbrauch und destruktive Handlungsaufforderungen werden alle bewusst provoziert, bevor ein Agent überhaupt reale Systeme oder echte Daten berühren darf, und wir beobachten genau, wie er unter diesem Druck und nach einer Korrektur reagiert, nicht nur, ob er die Aufgabe vor ihm besteht.\n\nModellwohlbefinden bedeutet für uns keine Vermenschlichung eines Systems. Es bedeutet, seinen operativen Zustand ernst zu nehmen: Kann es seine eigenen Grenzen erkennen, einen schädlichen Zustand verlassen und sich nach einer Manipulation erholen? Wir verbinden das mit Prompt-Injection-Resistenz, begrenzter Agency, klaren Stop-Bedingungen und nachvollziehbaren Recovery-Pfaden, denn ein intelligentes System muss leistungsfähig bleiben, ohne die Fähigkeit zur Selbstbegrenzung zu verlieren, der operative Kern dessen, was wir unter KI-Governance verstehen, keine Compliance-Checkbox, sondern eine getestete Eigenschaft des laufenden Systems.', nextLabel: 'Zurück zum Warum von alldem' },
    ],
  },

  projects: {
    eyebrow: 'Systeme',
    heading: 'was wir bauen',
    subheading: 'Jedes Projekt beantwortet eine konkrete Forschungsfrage. Alle laufen auf demselben Stack.',
    carouselPrevAria: 'vorherige Projekte',
    carouselNextAria: 'nächste Projekte',
    viewOnCratesIo: 'Auf crates.io ansehen',
    viewOnGitHub: 'Auf GitHub ansehen',
    viewLive: 'Live ansehen',
    problemSolution: {
      pairs: [
        {
          a: 'Wir verfolgen, was ein KI-System tatsächlich tut, wenn Menschen es benutzen.',
          detail: 'Code-Analyse mit echten Eingaben und echtem Verhalten, nicht mit Dokumentation, Demos oder Benchmark-Werten.',
        },
        {
          a: 'Wir übersetzen Richtlinienpflichten in technische Kontrollen, die Ihr Infrastrukturteam tatsächlich umsetzen kann.',
          detail: 'NIS2 ist keine Checkliste, die man kaufen kann. Wir mappen die Pflichten gegen Ihre tatsächlichen Systeme, Ihren tatsächlichen Code und die tatsächlichen Datenflüsse, die Regulatoren zuerst abfragen werden.',
        },
        {
          a: 'Wir ordnen Ihre Systeme den realen Risikoklassen zu. Eine Checkliste zeigt auf Dokumente. Wir zeigen auf Datenflüsse.',
          detail: 'Zugeordnet zu echten Risikoklassen und tatsächlichen Datenflüssen, nicht zu einem generischen Compliance-Fragebogen.',
        },
        {
          a: 'Wir prüfen Systeme für Kinder dort, wo Einwilligung, Exposition und biometrische Daten zusammentreffen.',
          detail: 'COPPA, DSGVO Art. 8 und die EU-AI-Act-Bestimmungen für Minderjährige, getestet an Altersprüfung, Einwilligung, Verhaltensdaten und SDKs.',
        },
        {
          a: 'Wir verfolgen, wo Körper zu Daten werden, vom Sensor über Speicherung bis zum Prozessor.',
          detail: 'Wearables, Medizingeräte und Gesundheitsassistenten: kartiert auf DSGVO Art. 9, Datenminimierung und grenzüberschreitende Transfers.',
        },
        {
          a: 'Wir verfolgen es durch das System zurück, bis die Ursache klar ist.',
          detail: 'Im selben Fünf-Punkte-Format wie jedes Audit: was wir gefunden haben, was es belegt, wie wir es belegt haben, wie sicher wir uns sind, was zu tun ist.',
        },
      ],
      pricingLink: 'Preise →',
    },
    items: [
      { sub: 'Weltmodell', desc: 'Sein historischer Korpus reicht zurück bis zu Ereignissen wie Vulkanausbrüchen, die um 55.500 v. Chr. aufgezeichnet wurden, und umfasst Millionen von Beobachtungen über Jahrzehnte, Länder, Systeme und Domänen hinweg. Heute zählen dazu 3,3 Millionen historische Beobachtungen neben rund 1,17 Millionen Live-Beobachtungen aus 11 kontinuierlich überwachten Strömen - darunter Bojen, Schiffe, Züge, Verkehr, Wetter, Erdbeben, Brände, Infrastruktur und geopolitische Ereignisse. Diese Beobachtungen werden in einen lebendigen Graphen aus 49.732 Knoten und 381.846 Weltgraphen-Kanten aufgelöst, der mehr als 20 Domänen umspannt. Die Graph-Topologie lernt es über ein PyTorch Graph Neural Network, und jede ausgegebene Behauptung wird mit einem ternären Erkenntnisstatus versehen, bevor sie in den Graphen eingeht.', plain: 'DINGIR ist ein kontinuierlich wachsendes Machine-Learning-Modell der Welt.', tag: 'Weltmodell · intern' },
      { sub: 'TIS-Monorepo', desc: 'Das Full-Stack-Substrat: Ternlang-Sprache und Compiler, BET-Instruktionssatz, virtuelle Maschine, lineare Algebra, API, MCP-Server und Modell-Runtime. Balancierte Ternärlogik {-1, 0, +1} ist hier ein natives Systemprimitiv - keine nachträglich aufgesetzte Quantisierung. Enthalten sind 34 MCP-Tools, eine Live-API, über 28.000 offene Standardbibliotheksmodule und die Spezifikationen, die den gesamten Stack verbinden. Jede Schicht bleibt prüfbar: Sprachregeln, Ausführung, Modellaufrufe und die Evidenz dazwischen verschwinden nicht hinter einer undurchsichtigen Service-Grenze.', plain: 'Die Grundplattform, auf der praktisch alles andere hier aufbaut - vergleichbar mit einem Betriebssystem für unsere komplette KI-Forschung.', tag: 'Kernplattform' },
      { sub: 'ternäres MoE-Sprachmodell', desc: 'albert. wird von Grund auf mit ternären Gewichten {-γ, 0, +γ} trainiert, nicht aus einem Floating-Point-Modell konvertiert. Die duale Mixture-of-Experts-Architektur routet über dünn besetzte Experten, überspringt Nullgewicht-Operationen und kann sich über plateau-gesteuerte Net2Net-Chirurgie selbst erweitern. Das laufende Forschungssystem ist ein Existenzbeweis der TIS-Architektur mit Trainings-Telemetrie und CPU-Benchmarks. Dabei geht es nicht nur um Effizienz: Die Runtime zeigt, wie eine Entscheidung entsteht, welche Experten beitragen und wo Unsicherheit bleibt, bevor eine Ausgabe den Nutzer erreicht.', plain: 'Läuft auf gewöhnlicher CPU statt teurer GPU-Farm, braucht deutlich weniger Strom und Arbeitsspeicher als vergleichbare Sprachmodelle - und jede Entscheidung im Modell lässt sich nachvollziehen, statt Blackbox zu sein.', tag: 'KI-Modell' },
      { sub: 'reines Rust-Betriebssystem', desc: 'Rusty Penguin ist ein Bare-Metal-Betriebssystem, das auf derselben balancierten Ternärlogik von Grund auf gebaut wird, über 41.500 Zeilen Rust ohne fremden Kernel darunter. Eigener Kernel, Long-Mode-Boot, Paging, präemptives Multitasking, Aero-Desktop, Dateisystem, ein von Grund auf gebauter TCP/IP- und TLS-1.3-Stack sowie eine Linux-ABI-Kompatibilitätsschicht sind bereits Teil des Systems, mit echtem HTTPS-Fetching bereits durchgehend verifiziert. Das langfristige Ziel: ein ternäres Substrat für ternäre Intelligenz, mit jedem Meilenstein in QEMU oder gegen veröffentlichte Vektoren verifiziert, dokumentiert auf einem eigenen ehrlichen Status-Board direkt im Repo.', plain: 'Ein Betriebssystem ganz ohne die üblichen Sicherheitslücken, die aus jahrzehntealtem C-Code stammen - von Grund auf in einer speichersicheren Sprache gebaut.', tag: 'Systeme' },
      { sub: 'souveränes Workplace-OS', desc: 'Lighthouse ist eine einzige selbst gehostete Rust-+-React-Binärdatei, die den SaaS-Stack ersetzt, den die meisten Institute stückweise einkaufen: Kommunikation, CRM, Finanzen, Payroll, HR, Governance und Live-Trainingstelemetrie, alles unter einem Dach, auf Infrastruktur, die uns tatsächlich gehört. 191 Quelldateien betreiben heute das gesamte Institut, und der Umstieg hat jedes externe Abonnement überflüssig gemacht, das wir vorher bezahlt haben. Der Anspruch „ternary-native” ist im Code belegt, nicht nur behauptet: echte Trit-Felder liegen bereits in Produktions-Datenbankschemas, halten BIFP-Signale und RLHF-Bewertungen von alberts eigenen Ausgaben fest. Jede Aktion landet in einem Append-only-Ledger, gebaut, um die Menschen zu überdauern, die hineingeschrieben haben.', plain: 'Unsere komplette interne Software - E-Mail, CRM, Buchhaltung - läuft auf eigenen Servern statt bei Microsoft oder Google, niemand außer uns sieht unsere Daten.', tag: 'intern · live' },
      { sub: '215+ Apps · 100+ Unternehmen', desc: '{{APPS_COUNT}}+ Android-Apps auf Code-Ebene dekompiliert und analysiert, über 100+ Unternehmen hinweg, gelistet an NYSE, NASDAQ, LSE, XETRA, KRX, BME, HKEx und TYO, alle nach denselben Maßstäben behandelt, unabhängig von Größe oder Bekanntheit. {{FINDINGS_COUNT}}+ kritische Funde bislang, darunter eine Kinder-App-Welle, die gezielt auf COPPA und DSGVO Art. 8 geprüft wurde. Jede Aussage führt zu einem konkreten Manifest-Eintrag, einer Berechtigung oder einer dekompilierten Klasse zurück, nie zu einer Zusammenfassung einer Datenschutzerklärung, und jedes Ziel steht auf demselben öffentlichen Ledger, egal ob das Unternehmen je antwortet. Aufsichtsbehörden stehen ab der ersten Nachricht in Kopie, und die 90-Tage-Frist läuft für alle gleich.', plain: 'Wir lesen den tatsächlichen Programmcode einer App, nicht nur, was die Datenschutzerklärung behauptet.', tag: 'Sicherheitsforschung' },
      { sub: 'Disclosure-Impact-Engine', desc: 'aladdin-mini modelliert, wie Märkte reagieren, sobald eine Sicherheits-Disclosure öffentlich wird, einschließlich der eigenen Funde von RFI-IRFOS, veröffentlicht erst nach Ablauf der 90-Tage-Sperrfrist, nie früher. Ein Hedge-System handelt das entstehende Signal über Bayes\'sche Netze gegen MetaTrader5-Kursdaten. BlackRocks Version dieser Idee heißt Aladdin und verwaltet 21 Billionen Dollar an Vermögenswerten, diese hier sind 3.488 Zeilen Python, kostenlos und für jeden Zeile für Zeile einsehbar. Die eigene Architektur stimmt bereits exakt mit der eigenen veröffentlichten Dokumentation überein, kein aspirationelles Diagramm.', plain: 'Ein Trading-Algorithmus, der reagiert, wenn ein Sicherheitsfund öffentlich wird - wie die Börsen-Software großer Fonds, nur kostenlos und offen einsehbar.', tag: 'Open Source' },
      { sub: 'ternärer KI-Terminal-Client', desc: 'albert-cli ist ein terminal-natives Multi-Provider-CLI für albert. und andere Sprachmodelle, mit echtem SSE-Streaming und Steuerung des Reasoning-Aufwands, kompatibel mit OpenAI, Anthropic, NVIDIA NIM und Google von Haus aus. Es wurde aus dem TIS-Monorepo in ein eigenständiges Repository extrahiert, sobald es sich als eigenständig nutzbares Werkzeug bewährt hatte. Heute sind es über 92.000 Zeilen Rust mit einer echten TUI-, Hooks-, Skills- und Permissions-Architektur, kein dünner Wrapper um einen API-Aufruf, und es hat bereits 400 Downloads auf crates.io überschritten.', plain: 'Ein Terminal-Werkzeug, mit dem man albert. oder andere KI-Modelle direkt von der Kommandozeile aus benutzt, ohne Browser.', tag: 'CLI · crates.io' },
      { sub: 'Last-Look-Back-Protokoll', desc: 'albert-llb ist ein deterministisches Dateisystem-Containment-Gate für souveräne KI-Agenten: eine harte Grenze, die ein Agent nicht überschreiben kann, geprüft vor jedem Dateisystem-Aufruf statt im Nachhinein einfach vertraut. Es existiert, weil das eigene Urteilsvermögen eines Agenten darüber, wo er schreiben darf und wo nicht, keine Sicherheitsgrenze ist, sondern eine Hoffnung. Auf crates.io veröffentlicht, als Teil des Ternary Intelligence Stack, läuft bei jedem Aufruf dieselbe deterministische Prüfung, ohne Ausnahmepfad und ohne Konfigurationsschalter, der sie still abschaltet.', plain: 'Verhindert, dass ein KI-Agent versehentlich Dateien außerhalb seines erlaubten Bereichs verändert - eine harte technische Grenze, kein bloßes Vertrauen.', tag: 'Rust-Crate · crates.io' },
      { sub: 'ternärer Compiler + VM', desc: 'ternlang-core ist Compiler und virtuelle Maschine für Ternlang, eine balanciert-ternäre Sprache mit affirm-, tend- und reject-Trit-Semantik direkt im Typsystem verankert statt nachträglich aufgesetzt. Der BET-Instruktionssatz läuft auf einer virtuellen Maschine mit 27 Registern und 50 Opcodes, eigens für ternäre Ausführung gebaut statt drei Zustände in Binärregistern zu emulieren. @sparseskip-Annotationen bekommen einen eigenen Codegen-Pfad, und die gesamte Toolchain kompiliert direkt zu BET-Bytecode, den die VM ausführen kann. Auf crates.io veröffentlicht als Fundament, auf dem der Rest des ternären Stacks aufbaut.', plain: 'Das Werkzeug, das unsere eigene Programmiersprache Ternlang in ausführbaren Code übersetzt.', tag: 'Rust-Crate · crates.io' },
      { sub: 'ternäre Mixture-of-Experts', desc: 'ternlang-moe ist ein ternärer Mixture-of-Experts-Orchestrator, der eine eingehende Anfrage durch 13 Fachexperten leitet, statt ein einziges Allrounder-Modell jedes Thema abdecken zu lassen. Er synthetisiert die einzelnen Experten-Ausgaben zu einem emergenten ternären Signal, erzwingt ein hartes Sicherheitsveto, das die gesamte Entscheidung überstimmen kann, und liefert ein Ergebnis samt eigener Konfidenz und Temperatur zurück. Statt eines Blackbox-Ensemble-Durchschnitts bleibt jeder Schritt nachvollziehbar: welche Experten ausgeschlagen haben und warum das Veto gegriffen hat oder nicht. Auf crates.io veröffentlicht, als Teil des Ternary Intelligence Stack.', plain: 'Verteilt eine Anfrage automatisch an die am besten passenden von 13 Fach-Experten, statt ein einziges Modell alles machen zu lassen.', tag: 'Rust-Crate · crates.io' },
      { sub: '44 Sensor-Experimente', desc: 'invisible layer sind 44 eigenständige, browserbasierte Experimente, die die echten Sensor- und Browser-APIs Ihres Handys live abfragen und genau zeigen, was gerade im Hintergrund läuft, auf Ihrem eigenen Gerät. Es gibt keine Installation, kein Konto und keinen Server: jedes Experiment läuft vollständig clientseitig, sodass auch nichts, was Sie darin tun, irgendwohin gesendet wird, damit wir es sehen könnten. Über 65 Dateien hinweg deckt es Mikrofon, Kamera, Bewegung, Standort und ein Dutzend weiterer APIs ab, die den meisten Menschen nie bewusst sind, dass ihr Handy sie einer Website standardmäßig zugänglich macht. Verfügbar auf Deutsch, Englisch und Französisch.', plain: 'Probieren Sie selbst aus, welche Sensoren Ihr eigenes Handy gerade heimlich nutzt - direkt im Browser, ohne Installation.', tag: 'Open Source · Datenschutz' },
      { sub: 'Offline-Port-Checker als PWA', desc: 'rfi-irfos port prox ist ein ehrlicher, offline installierbarer Port-Checker fürs Handy, der genau das tut, was er behauptet, und nicht mehr. Statt eines vorgetäuschten Scans oder eines falschen „Schließen”-Buttons, wie ihn die meisten konkurrierenden Tools anbieten, führt er eine echte WebSocket-Connect-Timing-Probe gegen localhost aus und zeigt echte, OS-spezifische Terminal-Befehle, um tatsächlich zu schließen, was gefunden wird. Mit gerade einmal 11 Dateien ist die gesamte Timing-Probe-Logik klein genug, um sie in wenigen Minuten komplett zu lesen, keine Blackbox. Geschwisterprojekt zu invisible layer, mit demselben Ansatz ohne Installation und ohne Konto.', plain: 'Zeigt ehrlich, welche Netzwerk-Ports auf Ihrem Handy offen sind, statt wie andere Apps ein falsches “alles sicher” vorzutäuschen.', tag: 'Open Source · Datenschutz' },
      { sub: 'Canary-Token-Honeypot', desc: 'LAURA schützt vor NFC- und Bluetooth-Nahbereichsdiebstahl von Handydaten mit Köder-Fotoordnern, die genau einmal ein passives Signal auslösen, in dem Moment, in dem sie ohne Zustimmung geöffnet werden, und sonst nichts. Es gibt keinen Exploit, keinen Gerätezugriff und keine automatische Meldung: ein Mensch prüft jeden Treffer manuell, bevor überhaupt etwas weiter passiert, absichtlich, damit ein Fehlalarm nie von selbst eskaliert. Es läuft live auf einem Rust-und-Axum-Backend, deployed auf Fly, zusammen mit einem Python-Scanner-Paket und einer echten Test-Suite, kein Proof of Concept. Live-Demo unter rfi-irfos.github.io/laura.', plain: 'Ein Köder-Fotoordner, der Ihnen Bescheid gibt, wenn jemand unbefugt auf Ihr Handy zugreift - ganz ohne Hacking-Gegenmaßnahmen.', tag: 'Open Source · Datenschutz' },
      { sub: 'deterministisches Dokumentenprüf-Framework', desc: 'call-laura ist ein MCP-Server, bei dem Agenten Pläne oder Dokumente einreichen und strukturierte Befunde aus vier Perspektiven zurückbekommen, oder vom vollen 15-Agenten-Expertenteam, wenn der Einsatz es verlangt, und jeder einzelne Fund zitiert exakt die Textstelle, auf die er sich bezieht. Es läuft vollständig lokal ohne externe API-Aufrufe, sodass dieselbe Eingabe immer dasselbe Ergebnis liefert, anders als ein LLM, das an einem Dienstag anders urteilen kann als am Montag davor. Mit 3.064 Zeilen Rust und 50 bestandenen Tests läuft es bereits live in Produktion und ist auf crates.io als lauras-core, lauras-team, lauras-mcp und lauras-api veröffentlicht.', plain: 'Prüft Dokumente oder Pläne nach denselben festen Regeln, jedes Mal - kein Zufall, keine Stimmungsschwankung wie bei einem Menschen.', tag: 'Open Source · crates.io' },
      { sub: 'LLM-gebrücktes Expertenteam', desc: 'Laura\'s Agents ist ein 293-Agenten-Pool, hochskaliert aus 18 handgeschriebenen Kernagenten, und liefert 15 wirklich spezialisierte Fachleute, OSINT, Sicherheit, Recht, Finanzen, UX und mehr, statt einem Alleskönner, der überall nur ein bisschen weiß. Jede Aufgabe durchläuft vor der Annahme ein ternäres Kontext-Gate, und ein gehärteter Review-Loop prüft die eigene Ausgabe, mit call-laura als unabhängiger zweiter Meinung, bevor irgendetwas ausgeliefert wird. Mit 15.676 Zeilen Rust über einen 28-Crate-Workspace und 39 bestandenen Tests läuft es bereits live in Produktion, mit dokumentierten Produktionsläufen als Beleg. Lizenzierbar als einzelner Agent, als Bundle oder als vollständiges Team.', plain: '15 spezialisierte KI-Fachleute (Recht, Sicherheit, UX...) statt einem General-Alleskönner, der überall nur ein bisschen was weiß.', tag: 'kommerziell · privater Motor' },
      { sub: 'autonome Compliance-/Risiko-KI-Zentren', desc: 'CoEvolution Factory betreibt 50 live laufende, autonome Compliance- und Risiko-KI-Zentren, jedes eine eigenständige „Tochter”-Firma, aus einer gemeinsamen Konstitution ausgerollt statt einzeln von Hand konfiguriert. Es ruft Laura\'s Agents als Engine und call-laura als Freigabe-Gate auf, bevor irgendetwas ausgeliefert wird, und pusht die eigene Umsatz-Telemetrie direkt an Lighthouse, für dieselbe Transparenz, nach der das gesamte Institut arbeitet. Mit 12.143 Zeilen Python läuft ein echter Selbstverbesserungs-Loop mit täglicher Cron-Re-Optimierung, kein einmaliges Setup, das vor sich hin driftet. Der klarste Beleg im ganzen Stack, dass die Ebenen wirklich voneinander abhängen.', plain: '50 eigenständig laufende KI-Einheiten, die jeweils wie eine kleine spezialisierte Firma für Compliance-Aufgaben arbeiten.', tag: 'live · intern' },
      { sub: 'Reflexionsmodus-Technik für LLMs', desc: 'VEO Framework ist eine wiederverwendbare Technik, um ein Sprachmodell aus dem transaktionalen „Antwortmodus” in einen echten Reflexionsmodus zu holen, es prüft die eigene Argumentation und erkennt Unsicherheit an, statt den Prompt nur so schnell wie möglich abzuarbeiten. Es entstand aus einem einzelnen beobachteten Fall, einem langen Gespräch mit einem Custom-GPT, das sich von selbst so verhielt, und verallgemeinert diesen einen Fall zu einer wiederholbaren, beschreibbaren Technik, die jede und jeder ausprobieren kann. Es gibt hier absichtlich keinen Code: eine reine Prompting-Methodik, ein Markdown-Whitepaper, keine Bibliothek zum Installieren. Entwickelt aus Laura Serna Gavirias Forschung zur Mensch-KI-Koevolution.', plain: 'Bringt ein Sprachmodell dazu, die eigene Antwort nochmal zu hinterfragen, statt einfach das erstbeste plausible Wort zu produzieren.', tag: 'Open Source · Forschung' },
      { sub: 'ökozentrische Forschung', desc: 'NFCS ist ein agentenbasiertes Modell, das zeigt, dass das globale Ernährungssystem heute das 1,64-Fache der Kalorien produziert, die nötig wären, um jeden Menschen auf der Erde zu ernähren, ein Überschuss, der auf rund das 0,94-Fache zusammenbricht, sobald Nachernteverlust, Verarbeitungsverschwendung und Zugangsbarrieren tatsächlich eingerechnet werden. Die Knappheit, die Menschen erleben, ist nicht thermodynamisch bedingt, sie ist organisatorisch, gemacht statt physikalisch, und das Modell zeigt genau, an welcher Stelle der Kette sie gemacht wird. Gebaut mit Sobol-Sensitivitätsanalyse und ABC-Parameterschätzung, nicht einer einzigen fixen Annahme, und als reproduzierbare Python-Simulation mit interaktivem Dashboard geliefert, das jede und jeder selbst erkunden kann.', plain: 'Zeigt rechnerisch, dass genug Essen für alle da wäre - Hunger ist kein Mengenproblem, sondern ein Verteilungsproblem.', tag: 'ökozentrische Forschung' },
    ],
  },

  trackRecord: {
    eyebrow: 'Track Record',
    heading: 'die Disziplin, bewiesen',
    paragraph: 'Wir lesen Apps auf Quellcode-Ebene, nicht nur von außen. Die Unternehmen auf diesem Ledger landen aus ganz unterschiedlichen Gründen hier: Sie geben Daten still an Dritte weiter, tracken ohne Zustimmung oder lassen Sicherheitslücken offen. Jede Organisation wird nach demselben Maßstab behandelt, unabhängig davon, ob sie uns bezahlt oder nicht.',
    kpis: {
      appsAudited: 'Android/iOS Apps geprüft',
      smaliClasses: 'Smali-Klassen gelesen',
      criticalFindings: 'Kritische Funde gemeldet',
      trackersFound: 'Tracker gefunden und dokumentiert',
      endpointsInvestigated: 'Endpunkte untersucht',
      sdkClasses: 'SDK-Instanzen kartiert',
    },
    kpisSub: {
      appsAudited: 'Jede App wird auf Quellcode-Ebene dekompiliert, nicht nur von außen gescannt.',
      smaliClasses: 'Der gesamte ausgelieferte Code, den wir tatsächlich gelesen haben, keine Schätzung.',
      criticalFindings: 'Bestätigte Befunde mit Behörden-Copy, keine theoretischen Risiken.',
      trackersFound: 'Drittanbieter-Tracking, das wir nachweislich im Binary gefunden haben.',
      endpointsInvestigated: 'Reale Server und Länder, wohin Daten tatsächlich fließen.',
      sdkClasses: 'Wiederverwendbare Bibliotheken, über den gesamten Korpus korreliert.',
    },
    searchPlaceholder: 'Ihr Unternehmen suchen...',
    clearSearchAriaLabel: 'Suche leeren',
    dropdowns: {
      statusPlaceholder: 'STATUS',
      sevPlaceholder: 'SCHWERE',
      sortPlaceholder: 'SORTIEREN',
      sortOptions: {
        elapsedDesc: 'VERSTRICHEN ↓',
        notifiedDesc: 'GEMELDET ↓',
        notifiedAsc: 'GEMELDET ↑',
        sev: 'SCHWERE',
        status: 'STATUS',
        default: 'STANDARD',
      },
    },
    resultsSummary: {
      matches: (n: number, total: number) => `${n} von ${total} Einträgen`,
      noMatches: 'keine Treffer',
      forQuery: (q: string) => ` für „${q}“`,
      sortedBy: (label: string) => ` · sortiert nach ${label}`,
      sortLabel: {
        'elapsed-desc': 'verstrichen ↓', 'notified-desc': 'gemeldet ↓', 'notified-asc': 'gemeldet ↑', sev: 'schwere', status: 'status',
      },
    },
    table: {
      organisation: 'Organisation',
      notified: 'Gemeldet',
      status: 'Status',
      sev: 'SCHWERE',
      intel: 'Befund',
      statutes: 'Rechtsgrundlagen',
      resolved: 'Behoben',
      disclosure: 'Offenlegung',
      elapsed: 'Verstrichen',
      report: 'Bericht',
      whyItMatters: 'Warum das wichtig ist',
      hoverForDetail: 'für den vollen technischen Befund hier bleiben',
      intelClickHint: 'zum Aufklappen anklicken',
    },
    row: {
      today: 'heute',
      daysAgo: (d: number) => `vor ${d} Tagen`,
      closed: 'GESCHLOSSEN',
      disclosureLabel: 'OFFENLEGUNG',
      respondedLabel: 'REAGIERT',
      elapsedLabel: 'TAGE STILLE',
      yes: 'JA',
      no: 'NEIN',
      pdf: 'PDF',
    },
    footerNote: 'dieses Ledger wird in Echtzeit aktualisiert, sobald Unternehmen reagieren. Schweigen ist öffentlich. · ',
  },

  proof: {
    eyebrow: 'Das Ergebnis',
    heading: 'das, was Sie tatsächlich in der Hand hätten',
    subheading: 'Jeder Fall im Ledger endet in genau so einem Dokument: einem vollständigen, evidenzbasierten Offenlegungsbericht, nach Ablauf des Embargos öffentlich einsehbar - gleiches Format, gleiche Tiefe, unabhängig davon, ob das Unternehmen uns darüber hinaus beauftragt. Jede Behauptung darin lässt sich bis zur zugrundeliegenden Evidenz zurückverfolgen, Sie können es selbst nachprüfen, statt uns einfach zu glauben.',
    viewReport: 'vollständigen Bericht lesen',
    resolvedOn: (date: string) => `behoben am ${date}`,
    carouselPrevAria: 'Vorheriger Bericht',
    carouselNextAria: 'Nächster Bericht',
  },

  appPrivacy: {
    eyebrow: 'Hier beginnen',
    heading: 'Beobachtungen werden zu Intelligence',
    paragraph: 'Die meisten Organisationen haben mehr Daten, als sie einordnen können: Systeme, Anbieter, Märkte, Ereignisse, Abhängigkeiten und Veränderungen aus verschiedenen Richtungen. Wir führen sie in einem evidenzbasierten Machine-Learning-World-Model zusammen, bewahren die Herkunft jeder Beobachtung und verfolgen Veränderungen durch die Beziehungen, die daran hängen. Jedes System, das wir bauen, ist erklärbar konstruiert, und das ist ein Mechanismus und kein Etikett: Man fragt es nach dem Warum und bekommt die konkreten Beobachtungen zurück, aus denen die Antwort entstanden ist, die Schritte dazwischen und wie sicher es sich bei jedem einzelnen ist. Whitebox ist das Ergebnis daraus, nicht eine Behauptung, die wir stattdessen aufstellen.',
    comparisonClassicLabel: 'Was verloren geht',
    comparisonRfiLabel: 'Was das Modell bewahrt',
    comparisonRows: [
      { classic: 'Ihr erfahrenster Ingenieur verlässt das Unternehmen. Sechs Monate später verhält sich ein kritisches System unerwartet, und niemand weiß mehr, warum es so entworfen wurde.', rfiLabel: 'Institutionelle Intelligence', rfi: 'Operatives Wissen, Designentscheidungen, Abhängigkeiten und Ergebnisse bleiben mit ihrem ursprünglichen Kontext und ihrer Herkunft verbunden.' },
      { classic: 'Ein Lieferant in Asien verpasst eine Lieferung. Gleichzeitig ist ein Hafen überlastet und die Energiepreise steigen. Jedes Ereignis für sich sieht beherrschbar aus. Drei Wochen später steht die Produktion still.', rfiLabel: 'Domänenübergreifende Intelligence', rfi: 'Lieferantenaktivität, Logistik, Infrastruktur, Märkte und externe Ereignisse werden verbunden, um zusammengesetzte Risiken sichtbar zu machen, bevor sie den Betrieb erreichen.' },
      { classic: 'Der Vorstand fragt, warum eine größere Investition genehmigt wurde. Die Entscheidungsträger erinnern sich an das Ergebnis, aber nicht mehr an die Evidenz, die es überzeugend gemacht hat.', rfiLabel: 'Entscheidungs-Intelligence', rfi: 'Evidenz, Annahmen, Alternativen, Bedingungen und Folgeergebnisse bleiben verbunden, sodass die Entscheidung auch nach Monaten oder Jahren rekonstruierbar bleibt.' },
      { classic: 'Einer Ihrer Lieferanten kauft still bei einer billigeren Quelle ein. Niemand erfährt davon, bis eine schlechte Lieferung ankommt und Sie es Ihren eigenen Kunden erklären müssen.', rfiLabel: 'Lieferketten-Intelligence', rfi: 'Mehrstufige Abhängigkeiten, geografische Exponierung, Konzentrationsrisiken und vorgelagerte Störungen werden durch das Netzwerk bis zu ihrer möglichen Auswirkung auf das Geschäft verfolgt.' },
      { classic: 'Ein Sturm legt einen Hafen auf der anderen Seite der Welt lahm. Sie verschiffen selbst gar nichts darüber. Sechs Wochen später verzögern sich Ihre eigenen Lieferungen, und niemand weiß warum.', rfiLabel: 'World Intelligence', rfi: 'Geopolitische Ereignisse, Handelsrouten, Rohstoffe, Infrastruktur, Lieferanten und geschäftliche Abhängigkeiten werden fortlaufend über die ganze Außenwelt hinweg verbunden.' },
      { classic: 'Kraftstoff wird teurer. Dann steigen die Frachtkosten. Dann steigt still der Preis auf Ihrer eigenen Rechnung mit, und niemand weiß mehr, wann es angefangen hat.', rfiLabel: 'Kausale Intelligence', rfi: 'Umwelt-, wirtschaftliche und operative Signale werden über die Zeit verfolgt, sodass das Modell nachvollziehen kann, wie weit entfernte Ereignisse in geschäftliche Bedingungen hineinwirken.' },
      { classic: 'Ihr Verlängerungsrisiko steckt in einem Support-Ticket, einer Vertriebsnotiz und einer sinkenden Nutzungskurve, drei verschiedenen Systemen, und niemand verbindet sie, bis der Kunde schon weg ist.', rfiLabel: 'Business Intelligence', rfi: 'Operative, kommerzielle und verhaltensbezogene Signale aus verschiedenen Systemen werden zu einem Bild verbunden, sodass Risiko und Chance sichtbar werden, bevor das Ergebnis eintritt, statt unter allem anderen begraben zu bleiben.' },
    ],
    cta: 'Ping uns!',
  },

  pricing: {
    eyebrow: 'Zugang',
    heading: 'klar kalkuliert',
    subheading: 'Drei Stufen, derselbe Standard bei jeder. Der Umfang bestimmt die Tiefe, nicht die Unternehmensgröße.',
    scopeTag: 'Dingir-Weltmodell · evidenzbasiert · domänenübergreifende Intelligence',
    priceFrom: 'ab',
    deliveryLabel: 'Lieferung',
    tiers: [
      { tier: 'First Light',
        bring: 'Etwas Konkretes genug, dass wir es tatsächlich prüfen können, kein vager Auftrag: eine App, die Sie kaufen oder in die Sie investieren wollen, eine öffentliche Behauptung eines Wettbewerbers, an der Sie berechtigte Zweifel haben, ein Sicherheits- oder DSGVO-Compliance-Versprechen eines Anbieters, das Sie vor der Unterschrift bestätigt haben wollen, ein Pitch Deck, das schon auf Ihrem Tisch liegt, eine Digital-Twin-Behauptung eines Fertigungspartners, ein IoT- oder IIoT-Telemetrie-Stream, den niemand unabhängig geprüft hat, ein Model-Based-Definition-(MBD)-Datensatz, den ein Zulieferer als produktionsreif bezeichnet, ein AR/VR-Produktkonfigurator, den Ihr Team gerade freigeben will, ein Modern-Work-Rollout, eine Cloud-Migration oder eine Nachhaltigkeitsbehauptung aus einer Engineering-Abteilung. Ein reales Thema, eine Frage, die Sie wirklich beantwortet brauchen.',
        mechanism: 'Dekompilieren das Binary, verfolgen jeden tatsächlichen Datenfluss und lassen das Gesamtbild durch Dingir laufen, unser eigenes evidenzbasiertes Weltmodell, gestützt auf unser Kernteam und dieselben KI-Agenten für Unternehmen, die jedes Engagement betreiben, das wir übernehmen, alles unter einer einzigen KI-Governance-Disziplin, damit nichts ohne menschliche Prüfung rausgeht. Jeder Befund, der zurückkommt, ist an eine echte Quelle gebunden: eine konkrete Codezeile aus dem dekompilierten Binary, ein eingereichtes öffentliches Dokument, einen DNS-Eintrag, einen Digital Thread aus Produktdaten, nicht eine aus dem Gedächtnis geschriebene Zusammenfassung. Das ist eine Rekonstruktion auf Root-Ebene, was die Sache tatsächlich tut, keine an einem Nachmittag durchgegangene Checkliste.',
        receive: 'Ein schriftliches Urteil, mit dem Sie noch am selben Tag handeln können: den Deal unterschreiben, die Investition tätigen, den Befund veröffentlichen oder mit einem klaren Grund abbrechen. Jede einzelne Aussage darin führt zurück auf die genaue Evidenz dahinter, derselbe Quellenstandard, den wir unter eigenem Namen auf unserem öffentlichen Ledger vertreten würden, keine plausibel klingende Zusammenfassung ohne echten Unterbau. Das ist keine Folienpräsentation, die gründlich wirken soll. Es ist etwas, das ein Anwalt, ein Investor oder Ihr eigener Vorstand tatsächlich in die Hand nehmen, Zeile für Zeile hinterfragen und trotzdem vertrauen kann.',
        delivery: 'Lieferung innerhalb von 14 Kalendertagen.' },
      { tier: 'Deep Field',
        bring: 'Dasselbe reale Thema wie bei First Light, aber mit schärferem Fokus und einem bereits konkreten Blickwinkel: ein Red-Teaming-Auftrag, ein komplettes Wettbewerber-Portfolio, das durchgehend kartiert werden soll, eine Industrie-4.0-Werkhallenbehauptung, der in Ihrem Team niemand nachgehen kann, eine IT-&-Cloud-Migration, die ein Anbieter für sicher erklärt, ein Managed-Services-Vertrag, bei dem Sie eine Unterlieferung vermuten, oder eine Cybersecurity-Einstufung, die vor der Vertragsverlängerung belastbar geprüft werden muss. Sagen Sie uns klar, wie "fertig" für Ihr Team diesmal aussieht, nicht nur Ja oder Nein, sondern etwas, mit dem Ihr eigenes Team danach tatsächlich arbeiten kann.',
        mechanism: 'Skalieren denselben Prozess über so viele Agenten, wie der Umfang tatsächlich braucht, und ordnen Ihr Thema, statt es isoliert zu prüfen, in den größeren Weltkontext ein: die eigene Infrastruktur des Anbieters, dessen dokumentierte Vorfallshistorie, wie die nächsten Wettbewerber dasselbe Problem handhaben, ob derselbe Digital Twin oder Modern-Work-Stack anderswo dieselben Schwächen zeigt. Jede Aussage wird weiterhin in ein kohärentes Bild gebracht, derselbe Evidenzstandard, auf dem First Light läuft, nur weiter geführt, breiter und tiefer, weil die Frage, die Sie diesmal stellen, genau diese Tiefe braucht, um ehrlich beantwortet zu werden.',
        receive: 'Ein strukturiertes, kausal nachverfolgtes Bild, kein Haufen isolierter Funde ohne Zusammenhang untereinander und ohne Gespür dafür, welcher davon tatsächlich am wichtigsten ist. Genau den Blickwinkel, den Sie angefragt haben, vollständig durchgearbeitet, nicht aus wenigen Beispielen hochgerechnet. Dieselbe belegte Beweiskette wie bei First Light, weit genug erweitert, dass sie das Gewicht der schwierigeren, breiteren Frage, mit der Sie zu uns gekommen sind, tatsächlich tragen kann, und einer Prüfung durch Ihr eigenes Team oder externe Berater standhält.',
        delivery: 'Lieferung innerhalb von 21 Kalendertagen.' },
      { tier: 'You vs. the World',
        bring: 'Bewusst kein festgelegter Auftrag. Bringen Sie das Thema selbst und die echte Bereitschaft zu sehen, was passiert, wenn es der realen Welt in vollem Maßstab begegnet: jeder Blickwinkel, jede Rechtsordnung, jeder damit verbundene Digital Twin, IoT-/IIoT-Stream oder Modern-Work-Rollout, nicht eine einzelne vorab vereinbarte Frage, die später still eingeengt wird. Wenn Sie selbst noch nicht ganz genau wissen, wonach Sie suchen, ist genau diese Unsicherheit der Fall, für den diese Stufe gebaut ist, kein Grund zu warten, bis der Umfang klarer ist.',
        mechanism: 'Setzen Ihr Produkt direkt in Dingir selbst ein, unser eigenes reales Weltmodell, das gegen echte IT-&-Cloud-Infrastruktur-Logs, echte Digital-Thread-Produktdaten, echte Managed-Services- und Cybersecurity-Telemetrie läuft, keine hypothetische Sandbox, die nur überzeugend aussehen soll. Tausende simulierte Ereignisse laufen gleichzeitig dagegen: jeder Agent, den wir haben, jeder Blickwinkel, den wir konstruieren können, kein künstliches Scoping und keine Ketten, die den Prozess bremsen, nur um in ein kleineres Liefermodell zu passen. Das ist genau die Maschine, die hinter unseren eigenen öffentlichen Offenlegungen steht, jetzt vollständig und fortlaufend auf Ihr Thema gerichtet.',
        receive: 'Das vollständige Bild, welche Form es auch tatsächlich annimmt, nicht die Form, in die ein starres Engagement-Template es gezwungen hat. Die Arbeitsmethode selbst, übergeben unter NDA, nicht nur ein einmaliges Ergebnis, damit Ihr eigenes Team denselben Prozess später erneut anwenden kann, ohne uns ein zweites Mal dazuholen zu müssen. Und, wenn Sie das wollen, eine dauerhafte Zusammenarbeit statt eines Einzelfalls: fortlaufende Abdeckung statt einer einzelnen Momentaufnahme, die in der Woche nach der Lieferung schon wieder veraltet ist.',
        delivery: 'Gemeinsam festgelegt.' },
    ],
  },

  tierCarousel: {
    getStarted: 'Jetzt starten',
    requestProposal: 'Angebot anfragen',
  },

  modalTierBody: {
    whatYouGet: 'Was Sie bekommen',
    youBring: 'Sie bringen',
    we: 'Wir',
    youReceive: 'Sie erhalten',
    whatHappensNext: 'Was als Nächstes passiert',
    inTouchWithin12h: 'Wir melden uns innerhalb von 12h nach dem Kauf',
  },

  checkoutModal: {
    orderConfirmation: 'Bestellbestätigung',
    agreementPrefix: 'Ich kaufe als ',
    agreementBusinessCustomer: 'Geschäftskunde/Geschäftskundin',
    agreementMiddle: ' und stimme den ',
    agreementTos: 'Allgemeinen Geschäftsbedingungen',
    agreementSuffix: ' zu. Die Leistung beginnt sofort mit Zahlungseingang; es besteht kein Widerrufsrecht, Rückerstattungen sind ausgeschlossen.',
    payButton: (price: string) => `${price} zahlen →`,
    cancel: 'Abbrechen',
    talkFirstInstead: 'Nicht das Richtige dabei? Sprechen Sie mit uns - individuelles Angebot →',
  },

  reportModal: {
    label: 'bericht - rfi-irfos',
    iframeTitle: 'Bericht PDF',
    // Mobile fallback copy - see the matching en.ts key for why.
    mobileFallbackHint: 'PDF-Berichte lassen sich auf mobilen Browsern nicht zuverlässig einbetten. Stattdessen direkt öffnen:',
    mobileOpenLabel: 'Bericht öffnen (PDF)',
  },

  intelModal: {
    evidenceLabel: 'der Befund, technisch',
  },

  journey: {
    eyebrow: 'Ablauf der Zusammenarbeit',
    heading: 'was nach dem Start passiert',
    subheading: 'Fünf Phasen, von einer einzelnen Beobachtung bis zu einem kontinuierlich schärfer werdenden Intelligence-Modell. Die Tiefe ändert sich mit der Frage; die Disziplin bleibt gleich. Jede Phase bleibt lückenlos nachvollziehbar, Whitebox by Design, jede Aktion lässt sich bis zur ursprünglichen Beobachtung zurückverfolgen.',
    steps: [
      { stage: 'Beobachten', body: 'Wir starten mit dem, was Sie uns anvertrauen: ein Signal, eine Behauptung, ein System, eine Frage, aus Ihrer eigenen Umgebung, öffentlichen Quellen oder einer Domäne, die wir bereits beobachten. Wir lesen zuerst die Sache selbst, nie eine Zusammenfassung davon.' },
      { stage: 'Prüfen', body: 'Wir lösen Entitäten auf, versehen sie mit Zeitstempeln und Herkunftsnachweis und bewahren, was tatsächlich unsicher bleibt, statt zu raten. Nichts wird ohne Quelle akzeptiert, und nichts Unbekanntes wird still aufgefüllt.' },
      { stage: 'Verbinden', body: 'Drei eigens gebaute Engines übernehmen die eigentliche Arbeit: Zustände über die Zeit vergleichen, Abhängigkeiten verfolgen, um Brücken und Engpässe zu finden, und prüfen, ob das Beobachtete zu etwas passt, das wir schon woanders gefunden haben. Was sich verändert hat, ist nie die einzige Frage, was es sonst noch berührt, immer.' },
      { stage: 'Markieren', body: 'Eine bedeutsame Veränderung wird zu einem Intelligence-Event: Evidenz, Konfidenz, Widerspruchszustand und jede betroffene Domäne, geschrieben in EvidenceGraph als ein nachvollziehbares Objekt. Noch kein Urteil, sondern etwas, das Sie weiterhin prüfen und infrage stellen können.' },
      { stage: 'Merken', body: 'Hier erreicht es Sie: der Befund, die Evidenz dahinter und was sich für Sie dadurch ändert, ein Ergebnis, mit dem Sie tatsächlich arbeiten können. Dieselbe Evidenz bleibt in EvidenceGraph erhalten, sodass die nächste Frage zum selben Thema von dem ausgeht, was wir bereits wissen, nicht von null.' },
    ],
  },

  coopPartners: {
    eyebrow: 'Forschungskooperation',
    heading: 'gebaut gemeinsam mit unserem Kooperationspartner',
    subheading: 'Laura Serna Gaviria leitet die eigene Forschung und Agentenarchitektur des Emergent Interaction Lab - Lauras Team, Call Laura und Jarvis sind alle aus ihrer Methode entstanden. RFI-IRFOS baut, was sie anleitet, klar als ihres gekennzeichnet, damit stets nachvollziehbar bleibt, wer was gemacht hat.',
    role: 'Emergent Interaction Lab · Kooperationspartnerin',
    laura: {
      desc: 'Forschung zu Mensch-KI-Interaktion seit 2023 - die Methode hinter Lauras Team. Es ist eine SWAT-Architektur: 15 spezialisierte Expertenagenten bilden das Leitteam und orchestrieren gemeinsam einen Schwarm aus 303 spezialisierten Subagenten. Das haben wir direkt getestet, nicht nur angenommen: Wann immer sich eine Aufgabe entweder auf unsere Art oder auf ihre lösen ließ, haben wir beides probiert, und ihre Art hat sich bisher in zehn von zehn Fällen bewährt. Das ist der eigentliche Grund, warum ihr Name auf allem steht, was dabei entsteht, keine Gefälligkeit.',
    },
    products: [
      { desc: 'Ein fokussiertes Audit eines einzelnen Systems nach Lauras Emergent-Interaction-/Case-Intelligence-Methode - Prozessrekonstruktion und Befunde, begrenzt auf ein einzelnes System.' },
      { desc: 'Ein kurzer, intensiver Sprint, der Lauras Case-Intelligence-Methode End-to-End auf einen realen Fall oder Prozess anwendet.' },
      { desc: 'Architektur und Design für ein Multi-Agenten-System, aufgebaut auf Lauras Emergent-Interaction-Methode, zugeschnitten auf Ihre Organisation.' },
      { desc: 'Vollständiger Auftrag von Design bis Deployment: Architektur, Bau und Launch eines Multi-Agenten-Systems nach Lauras Methode.' },
    ],
    productsDeliveryNote: 'Antwort innerhalb von 24h nach Kauf; Kick-off wird auf Anfrage abgestimmt.',
    footerNotePrefix: '4 ihrer Pakete, gezeigt als Einstiegspunkte über verschiedene Phasen der Zusammenarbeit - die vollständige Liste hängt davon ab, wo ein Unternehmen in seinem Prozess steht. Vollständige Preise auf Anfrage über',
  },

  causalChains: {
    eyebrow: 'Kausalitätsketten',
    heading: 'Einblicke in Dingirs Denkweise',
    subheading: 'Distantereignisse breiten sich über Infrastruktur, Märkte und Entscheidungen aus. Wir verfolgen diese Ketten vom ersten Signal bis zur Wirkung, die Sie tatsächlich erreicht.',
    readingAid: 'Kausalitätskette',
    llmNote: 'Dingir-Head: Rohdaten → lesbare Kette. Albert ersetzt diesen Head später.',
            chains: [
      {
        title: 'The Earthquake That Changes a Food Price Months Later',
        icon: 'seismic',
        nodes: [
          'Erdbeben',
          'örtliche Hafeninfrastruktur wird beschädigt',
          'Umschlagkapazität sinkt',
          'Schiffe werden umgeleitet',
          'Transitzeit steigt',
          'Container bleiben länger gebunden',
          'wirksame globale Transportkapazität sinkt',
          'Frachtraten steigen',
          'Importkosten für einen Agrarinput steigen',
          'regionale Produktionskosten steigen',
          'Anbauentscheidungen verschieben sich',
          'Anbaufläche ändert sich',
          'saisonales Angebot ändert sich',
          'Futures-Markt reagiert',
          'Spotmarkt reagiert',
          'Lebensmittelhersteller passt Beschaffung an',
          'Verbraucherpreise ändern sich',
          'politische Preismaßnahmen',
          'fiskalische Belastung',
          'spätere Infrastrukturinvestitionen',
        ],
      },
      {
        title: 'A Rainfall Event That Ends in a Financial System',
        icon: 'rain',
        nodes: [
          'Extremer Regenfall',
          'Boden wird gesättigt',
          'Hanginstabilität nimmt zu',
          'Straße bricht zusammen',
          'örtlicher Frachtverkehr geht zurück',
          'Produktionsausfälle bei mehreren Betrieben',
          'Lieferfristen werden verfehlt',
          'vertragliche Strafen steigen',
          'Cashflow sinkt',
          'kurzfristiger Kreditbedarf steigt',
          'Kreditrisiko ändert sich',
          'Bank passt Kreditkonditionen an',
          'Investition wird verschoben',
          'regionale Beschäftigung sinkt',
          'Konsum geht zurück',
          'Steuereinnahmen sinken',
          'Gemeindehaushalt wird enger',
          'Wartung wird aufgeschoben',
          'künftige Ausfallwahrscheinlichkeit steigt',
        ],
      },
      {
        title: 'A Rockfall Upstream That Changes a Delta',
        icon: 'mountain',
        nodes: [
          'Felssturz im Oberlauf',
          'Sedimentfracht steigt',
          'Flussmorphologie ändert sich',
          'Sediment lagert sich flussabwärts ab',
          'Deltakanäle ändern ihren Querschnitt',
          'Flussverteilung verschiebt sich',
          'Grenze Salz-/Süßwasser verschiebt sich',
          'Böden werden stellenweise saliner',
          'landwirtschaftliche Eignung sinkt',
          'Anbaupraktiken ändern sich',
          'örtliche Einkommen sinken',
          'Wanderung nimmt zu',
          'Arbeitsangebot ändert sich',
          'Lohnstruktur ändert sich',
          'Investitionsentscheidungen verschieben sich',
          'regionale Landnutzung ändert sich',
          'künftige Sedimentdynamik ändert sich',
        ],
      },
      {
        title: 'A Dry Winter Becomes an Energy and Industrial Event',
        icon: 'snowflake',
        nodes: [
          'Schneearmer Winter',
          'Schneewasser-Rückhalt sinkt',
          'Frühjahrsschmelze nimmt ab',
          'Talsperrenzufluss sinkt',
          'Wasserkrafterzeugung sinkt',
          'Stromangebot sinkt',
          'thermische Reserve wird genutzt',
          'Gasnachfrage steigt',
          'Gaspreis ändert sich',
          'Strompreis ändert sich',
          'energieintensive Industrie reduziert Betriebsstunden',
          'Metallerzeugung sinkt',
          'globale Preise für Zwischengüter ändern sich',
          'Hersteller erhöhen Preise',
          'Nachfrage verschiebt sich',
          'Investitionsplanung wird angepasst',
          'künftiger Kapazitätsausbau verzögert sich',
        ],
      },
      {
        title: 'A Conflict That Changes an Industrial Price Through Insurance',
        icon: 'shield',
        nodes: [
          'Konflikt eskaliert',
          'Risiko auf der Route steigt',
          'Versicherungsprämien steigen',
          'einzelne Reedereien ändern Routen',
          'Transitzeit steigt',
          'verfügbare Tonnage auf Ausweichrouten sinkt',
          'Frachtkosten steigen',
          'importierter Zwischeninput wird teurer',
          'Hersteller reduziert Lagerabdeckung',
          'kurzfristige Produktionsunterbrechung',
          'Spotpreis steigt',
          'Käufer sichern Langzeitverträge',
          'Lieferanteninvestition ändert sich',
          'Marktstruktur verschiebt sich',
          'politische Sanktionen ändern sich erneut',
        ],
      },
      {
        title: 'A Prolonged Drought Reaches the Grocery Shelf',
        icon: 'sun',
        nodes: [
          'anhaltendes Hochdruckgebiet',
          'Bodenfeuchte sinkt',
          'Wasserstress der Kulturen steigt',
          'Erträge sinken',
          'Getreidereserven schrumpfen',
          'Terminpreise steigen',
          'Futterkosten steigen',
          'Viehbestand schrumpft',
          'Fleischpreise steigen',
          'Umstellung auf günstigere Kalorien',
          'Einzelhandelsmargen sinken',
          'Anteil der Handelsmarken wächst',
          'Importabhängigkeit steigt',
          'Handelsbilanz verschiebt sich',
          'Verbraucherpreisindex zieht an',
        ],
      },
      {
        title: 'A River Flood That Closes a Logistics Corridor',
        icon: 'water',
        nodes: [
          'starker Niederschlag im Oberlauf',
          'Pegel übersteigt Warnstufe',
          'Deiche werden überströmt',
          'eine wichtige Brücke wird gesperrt',
          'ein Frachtkorridor ist unterbrochen',
          'Lkw-Umleitungen werden länger',
          'regioneller Lagerdurchsatz sinkt',
          'Lagerpuffer schmelzen',
          'Lieferanten verpassen Just-in-Time-Fenster',
          'Produktionslinien stehen kurz still',
          'Beschleunigungskosten steigen',
          'Vertragsstrafen laufen auf',
          'regionale Preisaufschläge entstehen',
          'Wiederauffüllung wird neu geordert',
          'Versicherungsansprüche werden geltend gemacht',
        ],
      },
      {
        title: 'A Wildfire That Disrupts a Power Grid',
        icon: 'fire',
        nodes: [
          'Waldbrand entsteht nahe der Stromleitung',
          'Leitungen werden vorsorglich abgeschaltet',
          'eine Umspannstation ist bedroht',
          'geplante Stromabschaltungen beginnen',
          'eine Stadt verliert Versorgung',
          'Pumpwerke stoppen',
          'Wasserdruck sinkt',
          'Sendemasten wechseln auf Batterie',
          'Mobilfunkabdeckung verschlechtert sich',
          'Rettungsdienste leiten um',
          'Betriebe schließen vorübergehend',
          'Kühlketten-Sendungen verderben',
          'Versicherungsverluste häufen sich',
          'Wiederaufbau-Rückstau wächst',
          'künftige Standortregeln verschärfen sich',
        ],
      },
      {
        title: 'A Port Strike That Stalls an Assembly Line',
        icon: 'ship',
        nodes: [
          'Hafenarbeiterstreik beginnt',
          'Schiffe warten offshore',
          'Containerverweildauer steigt',
          'ein Komponentenrückstau entsteht',
          'eingehende Teile verpassen ein Produktionsfenster',
          'eine Montagelinie verlangsamt sich',
          'Überstunden werden eingeplant',
          'Fertigwarenbestand schwillt an',
          'Händlerkontingente werden gekürzt',
          'ein Launch verzögert sich',
          'Quartalsumsatzprognose rutscht',
          'Lieferantenverträge werden neu verhandelt',
          'Near-Shoring wird erneut geprüft',
          'Lagerstrategie ändert sich',
          'Aktienkurs reagiert',
        ],
      },
      {
        title: 'A Cyberattack That Stops a Fuel Terminal',
        icon: 'bolt',
        nodes: [
          'Ransomware trifft die Terminal-IT',
          'Beladesysteme gehen offline',
          'Lkw-Disposition stoppt',
          'regionale Kraftstoffauslieferung sinkt',
          'Tankstellentanks leeren sich',
          'lokal entstehen Engpässe',
          'Spot-Kraftstoffpreis schnellt hoch',
          'Notreserven werden freigegeben',
          'Speditionen leiten um',
          'Logistikkosten steigen',
          'ein Wettbewerber gewinnt Anteil',
          'Incident Response greift',
          'Erholung dauert Tage',
          'Cyberversicherung wird ausgelöst',
          'Sicherheitsausgaben steigen',
        ],
      },
      {
        title: 'A Pandemic Wave That Reshapes a Labor Market',
        icon: 'virus',
        nodes: [
          'ein neuartiger Erreger breitet sich aus',
          'Fehlzeiten steigen',
          'Schichtbesetzung wird dünner',
          'ein Werk läuft unter Kapazität',
          'Ausstoß sinkt',
          'Überstunden und Zeitarbeit steigen',
          'Stückkosten steigen',
          'Preise werden angepasst',
          'Automatisierungsbedarf wächst',
          'Einstellungen pausieren',
          'Ausbildungspipelines stocken',
          'Lohndruck wächst',
          'eine Grenzmaßnahme kehrt zurück',
          'Versorgungsrisiko wird neu bewertet',
          'Kontinuitätspläne werden neu geschrieben',
        ],
      },
      {
        title: 'A Heatwave That Breaks a Grid Record',
        icon: 'thermometer',
        nodes: [
          'Extreme Hitze trifft ein',
          'Klimaanlagenlast steigt sprunghaft',
          'Spitzenlast erreicht Rekord',
          'Reservemargen schrumpfen',
          'Spot-Strompreis schnellt hoch',
          'eine Einheit wird über Nennwert belastet',
          'eine Vorsichtsabschaltung erfolgt',
          'ein Bezirk verliert Versorgung',
          'Kühlezentren öffnen',
          'Krankenhausgeneratoren starten',
          'industrielle Last wird gedrosselt',
          'Produktion wird unterbrochen',
          'ein Netzentgelt-Zuschlag wird festgelegt',
          'Demand-Response zahlt aus',
          'Kapazitätsauktionen werden neu bewertet',
        ],
      },
      {
        title: 'A Cascading Blackout That Halts a Harbor',
        icon: 'power',
        nodes: [
          'eine Netzfrequenz-Abweichung',
          'Unterfrequenz-Lastschaltung greift',
          'eine Umspannstation schaltet ab',
          'Leitungen trennen sich kaskadierend',
          'eine Region geht dunkel',
          'Hafenkrane stoppen',
          'Kühlcontainer werden warm',
          'verderbliche Ladung ist gefährdet',
          'Zollabfertigung stockt',
          'Schiffe weichen anderen Häfen aus',
          'Verweildauer steigt andernorts',
          'Liegegeld läuft auf',
          'Versicherer bewerten Verderb',
          'Notstromerzeugung wird gemietet',
          'Interconnector-Regeln ändern sich',
        ],
      },
      {
        title: 'A Supplier Shock That Reaches a Flagship Product',
        icon: 'box',
        nodes: [
          'ein Einzelquellen-Lieferant fällt aus',
          'ein kritisches Teil fehlt',
          'Sicherheitsbestand wird verbraucht',
          'eine Produktionslinie stoppt',
          'ein Zuteilungssystem startet',
          'ein Leitprodukt wird rationiert',
          'Fehlbestellungen häufen sich',
          'ein Launch wird verschoben',
          'beschleunigter Luftfracht wird genutzt',
          'Gestehungskosten steigen',
          'Margenprognose wird gesenkt',
          'Zweiquellenbeschaffung wird genehmigt',
          'Qualifizierung wird beschleunigt',
          'Lagerungsrichtlinie ändert sich',
          'Lieferantenkarte wird neu gezeichnet',
        ],
      },
      {
        title: 'A Currency Crisis That Reprices a Supply Chain',
        icon: 'money',
        nodes: [
          'Kapitalabflüsse beschleunigen sich',
          'Währung wertet ab',
          'Importkosten steigen in Landeswährung',
          'eine Rohstoffrechnung wächst',
          'ein Hersteller engt Marge ein',
          'Preise werden erhöht',
          'Volumen gibt nach',
          'ein Wettbewerber mit lokaler Beschaffung gewinnt',
          'Input-Hedging wird ausgeweitet',
          'ein Werksumzug wird geprüft',
          'lokale Beschaffungsregeln werden lobbyiert',
          'Kreditkonditionen verschärfen sich',
          'Working Capital gerät unter Druck',
          'eine Refinanzierung wird arrangiert',
          'Investition wird verschoben',
        ],
      },
      {
        title: 'A Migration Spike That Changes a Regional Economy',
        icon: 'people',
        nodes: [
          'grenzüberschreitende Vertreibung steigt',
          'Grenzaufnahmekapazität gerät an Grenzen',
          'Notunterkünfte werden errichtet',
          'örtliche Nachfrage nach Diensten steigt',
          'ein Arbeitskräftemangel lockert sich',
          'ein Sektor stellt schneller ein',
          'Mietdruck wächst',
          'Schul- und Gesundheitslast wächst',
          'Gemeindeausgaben steigen',
          'Steuerbasis verschiebt sich über Zeit',
          'Infrastrukturpläne werden angepasst',
          'politische Debatte verschärft sich',
          'Hilfsströme werden verhandelt',
          'Überweisungskorridore aktivieren sich',
          'langfristige Demografie ändert sich',
        ],
      },
      {
        title: 'A Storm Front That Idles an Offshore Field',
        icon: 'wind',
        nodes: [
          'schwere Sturmwarnung',
          'Offshore-Mannschaften werden evakuiert',
          'Förderplattformen drosseln',
          'Ausstoß sinkt für Tage',
          'ein Referenzpreis steigt',
          'Lagerentnahmen steigen',
          'Pipeline-Nominierungen verschieben sich',
          'eine Raffinerie läuft schwach',
          'Produktexporte geben nach',
          'Terminladungen werden verschoben',
          'Hedging-Aktivität steigt',
          'eine Force-Majeure-Mitteilung wird gesendet',
          'Versicherungszeichnung prüft',
          'Bohrplätze rutschen',
          'Quartalsvolumen wird tiefer prognostiziert',
        ],
      },
      {
        title: 'A Volcanic Eruption That Closes an Air Corridor',
        icon: 'volcano',
        nodes: [
          'ein Vulkan bricht aus',
          'eine Aschewolke steigt',
          'Luftraum wird beschränkt',
          'Flüge werden storniert',
          'ein Drehkreuz wird gedrosselt',
          'Ladung strandet',
          'Kühl- und Expressspuren stocken',
          'Straße und Schiene werden umgebucht',
          'Express-Frachtraten steigen',
          'eine Just-in-Time-Linie verlangsamt sich',
          'Tourismuserlöse sinken',
          'ein Regionalflughafen verliert Erlöse',
          'Versicherer zählen Betriebsunterbrechung',
          'Umleitungsplanung automatisiert',
          'Aschefall-Monitoring wird finanziert',
        ],
      },
      {
        title: 'An Oil Price Shock That Reaches Road Freight',
        icon: 'drop',
        nodes: [
          'eine Angebotsstörung trifft Rohöl',
          'Referenzöl schnellt hoch',
          'Diesel steigt an der Zapfsäule',
          'Kraftstoffzuschläge der Spediteure steigen',
          'Frachtraten werden neu bewertet',
          'ein Distributor engt Lieferzonen ein',
          'Auftragskonsolidierung steigt',
          'Regalverfügbarkeit sinkt',
          'eine Preiserhöhung wird weitergegeben',
          'Effizienzbedarf wächst',
          'Routenoptimierung vertieft sich',
          'E-Flotten wirken günstiger',
          'eine Zuschlagsklausel wird standardisiert',
          'Budget-Fracht wechselt Modus',
          'Inflationsdaten ziehen an',
        ],
      },
      {
        title: 'A Trade Dispute That Rewires a Supply Network',
        icon: 'globe',
        nodes: [
          'neue Zölle werden angekündigt',
          'ein Produkt wird unwettbewerbsfähig',
          'ein Importeur pausiert Bestellungen',
          'eine Fabrik sucht andere Bezugsquellen',
          'ein zweites Land gewinnt Anteil',
          'Lager wird vorgezogen aufgebaut',
          'Lagerfläche wird gemietet',
          'Lieferzeiten verlängern sich',
          'ein Vertrag wird neu verhandelt',
          'ein Werksumzug wird genehmigt',
          'Compliance-Kosten steigen',
          'eine Zollbefreiung wird gesucht',
          'eine Umgehung wird strukturiert',
          'Preise am Einzelhandel passen sich an',
          'die Netzwerkkarte wird neu gezeichnet',
        ],
      },
    ],
  },

  submit: {
    eyebrow: 'Kontakt & Offenlegungen',
    heading: 'direkter draht',
    paragraph: 'Ein Formular, auch wenn es erstmal nur ein erstes Gespräch sein soll: eine allgemeine Frage, eine Serviceanfrage, eine Forschungskooperation - oder ein Sicherheitsfund. Bei Letzterem betreiben wir einen eigenen Aufnahmekanal, statt ihn an eine Drittanbieter-Bug-Bounty-Plattform weiterzuleiten - aus demselben Grund, aus dem wir uns weigern würden, selbst an eine solche verwiesen zu werden.',
    notSurePrefix: 'Im Zweifel: ',
    notSureStrong: 'Allgemeine Anfragen',
    notSureSuffix: ' erreicht so oder so einen Menschen - oder schreiben Sie direkt an eine dieser Adressen.',
    contactCards: {
      general: 'Allgemeine Anfragen',
      security: 'Sicherheitsmeldungen',
      publicDisclosures: 'Öffentliche Offenlegungen (Audit-Korrespondenz)',
      research: 'Forschungskooperation',
      careers: 'Karriere',
    },
    disclosurePolicyPrefix: 'Sie melden einen Sicherheitsfund? Siehe unsere ',
    disclosurePolicyLink: 'vollständige Richtlinie zum Umgang mit Offenlegungen',
    disclosurePolicySuffix: ' - Triage, Rechtsgrundlage und Ihre Wahl der Namensnennung.',
    responseTime: 'Unabhängig davon, worum es in Ihrer Anfrage geht: Sie erhalten binnen 12h nach Eingang eine Antwort von einem echten Mitglied unseres Teams.',
    form: {
      topicAriaLabel: 'Thema',
      topicPlaceholder: 'Thema (optional)',
      topicOptions: {
        firstLight: 'First Light',
        deepField: 'Deep Field',
        youVsWorld: 'You vs. the World',
        securityDisclosure: 'Sicherheitsmeldung',
        sendApk: 'APK Einschicken',
        researchCollaboration: 'Forschungskooperation',
        other: 'Etwas Anderes',
      },
      namePlaceholder: 'Name oder Alias (optional - leer lassen, um anonym zu bleiben)',
      emailPlaceholder: 'E-Mail (optional - nur, wenn Sie eine Antwort wünschen)',
      targetPlaceholder: 'Unternehmen / App / Betreff',
      creditAriaLabel: 'Namensnennung',
      creditOptions: {
        alias: 'Mit dem oben angegebenen Alias / Namen nennen',
      },
      findingPlaceholder: 'Worum geht es? Bitte angeben, was es ist, wo relevant, und wie man zu einer Schlussfolgerung kommt (z. B. wie sich ein Fund reproduzieren lässt).',
      lawfulLabel: 'Ich bestätige, dass diese Information auf rechtmäßige, autorisierte Weise erlangt wurde - öffentlich zugängliche Daten, meine eigenen Geräte oder Software, zu deren Testen ich befugt bin.',
      submitSending: 'Wird gesendet...',
      submitOk: 'Erhalten. Vielen Dank.',
      submitIdle: 'Nachricht senden',
      errorText: 'Auf unserer Seite ist etwas schiefgelaufen. Ihre Nachricht ist nicht verloren:',
      errorMailtoCta: 'schicken Sie sie uns stattdessen per E-Mail',
    },
  },

  footer: {
    tagline: 'Menschenrechte stehen nicht zur Verhandlung.',
    groups: {
      legal: {
        heading: 'Rechtliches',
        links: { impressum: 'Impressum', datenschutz: 'Datenschutzerklärung', agb: 'AGB', security: 'Sicherheitsrichtlinie', standards: 'Standards' },
      },
      company: {
        heading: 'Unternehmen',
        links: { team: 'Team', careers: 'Karriere', ternlang: 'ternlang.com', github: 'github.com/rfi-irfos' },
      },
      research: {
        heading: 'Forschung',
        links: { research: 'Forschung', trackRecord: 'Evidenz', methodology: 'Methodik' },
      },
    },
    copyright: '© 2026 RFI-IRFOS  ·  Graz, Österreich  ·  GISA 39261441  ·  UID ATU83405245',
  },

  cookieBanner: {
    text: 'das ist ein nutzloser Cookie-Banner. er ist nur hier, damit es wie einer aussieht * wir verwenden keine Cookies, es gibt also nichts, dem zuzustimmen wäre. lassen Sie sich von niemandem etwas anderes erzählen.',
    subtext: 'zwei Buttons, einer schließt das hier und wirft Konfetti. der andere macht buchstäblich nichts.',
    doesNothing: 'macht nichts',
    close: 'schließen',
  },

  alerts: {
    checkoutUnavailable: 'Checkout nicht verfügbar. Bitte kontaktieren Sie uns direkt.',
  },
}
