// Single source-of-truth English content object for the homepage (PublicSite.tsx
// + components/sections/*.tsx). Every string here was moved VERBATIM out of the
// already-shipped, approved English copy - nothing was rewritten or "cleaned up"
// during extraction. `de.ts` implements the same `Content` shape (checked via
// `DE: Content = {...}`), so a missing/renamed key is a compile error there.
//
// Deliberately left OUT of this content layer (per the i18n task's own scope
// call): the Track Record ledger's row data (AUDIT_HIGHLIGHTS/AUDIT_META/
// AUDIT_STATUTES in TrackRecord.tsx - 300+ real disclosure rows, English-only),
// STATUS_META's status codes (WAITING/ACK/RESOLVED/etc - technical ledger
// vocabulary, not prose), raw numbers/prices/ISO citations/emails/URLs, and the
// WKO footer SVG.

export const EN = {
  nav: {
    links: {
      research: 'Research',
      projects: 'Systems',
      trackRecord: 'Evidence',
      pricing: 'Access',
      submit: 'Submit',
    },
    themeLabel: { light: 'Light', dark: 'Dark', hc: 'High contrast' } as Record<'light' | 'dark' | 'hc', string>,
    themeTitle: (label: string) => `Theme: ${label} (click to switch)`,
    themeAria: (label: string) => `Current theme ${label}, click to switch theme`,
    menuAria: 'Menu',
    localeTitle: (label: string) => `Language: ${label} (click to switch)`,
    localeAria: (label: string) => `Current language ${label}, click to switch language`,
  },

  hero: {
    headline: 'Rethink the Obvious.',
    headlineEmphasisIndex: 2,
    subtitlePrefix: 'Interdisciplinary',
    subtitleSuffix: ' Research Facility for Open Sciences',
    identity: 'We craft what holds under load and expose what was destined to fail. No theater, no high-visibility vests.',
    stats: {
      researchAreas: 'research areas',
      researchAreasSub: 'combined',
      openSourceProjects: 'systems',
      openSourceProjectsSub: 'working together',
      dataPointsMonitored: 'data points monitored',
      worldModel: 'evidence-first ML world model',
      agents: 'handcoded agents',
    },
    ctaTrackRecord: 'Track Record',
    ctaBookUs: 'Book us!',
  },

  research: {
    eyebrow: 'Areas of Magnification',
    heading: 'where our attention falls',
    subheading: 'How complex systems behave: how evidence becomes structure, how relationships change over time, and where one butterfly can move an entire network.',
    areas: [
      { title: 'Ethic Audits & Minor Protection', plain: 'The children on the other side of this screen inherit the world we are building now. One day, they will have to live in it, shape it, and carry it forward. That is why we start here.', desc: 'We build systems whose consequences can last far longer than the people who build them. A child does not choose the data systems, technologies or infrastructure that shape their environment, yet they will live with what those systems become. Minor protection makes that responsibility concrete. We look at what happens before consent, before the interface, before anyone notices: which SDKs activate, what data moves, and which decisions are already being made.\n\nWe test those systems against real consent flows, real technical behaviour and the COPPA and GDPR Article 8 findings already documented on our public ledger. The principle is simple: what we build today must remain defensible to the people who inherit it tomorrow.', nextLabel: 'The Ground Everything Else Stands On' },
      { title: 'Ternary AI & Smart Computing', plain: 'A binary system must choose yes or no even when the evidence lives somewhere in between. Ternary gives that uncertainty a state of its own: −1, 0, +1. Not everything has to be decided immediately, and uncertainty does not have to become false certainty just to make a decision possible.', desc: 'We wanted computing that could work with that uncertainty instead of discarding it before the decision. The third state gives unresolved, unobservable or contradictory information somewhere real to live. That changes more than representation. It changes system behaviour: sometimes the safest and most intelligent action is to wait.\n\nThat is why we built Ternlang, our own programming language directly on the {-1, 0, +1} trit. It now forms the runtime on which albert. is trained and coordinates our production agent swarm. Ternary computing is not a thought experiment for us. It is an architecture we are already running. Patent pending A50296/2026.', nextLabel: 'Trits Power the World Model' },
      { title: 'World Models & Cross-Domain Intelligence', plain: 'A language model can describe a supply chain perfectly and still miss that a failure at the other end of the network will shut down a factory days later. A world model holds those relationships themselves: states, dependencies, changes, and what follows from them.', desc: 'We kept running into investigations where the decisive evidence was scattered across systems. A signal lived in one place, its cause in another, and the connection only became visible after the damage had already happened. That is the gap we want to close.\n\nAlongside albert., our language model, we are building Dingir, our own world model for the physical world. It connects observations across time, geography and domains and follows changes into the systems they can actually affect. Not as a collection of documents, but as a continuously evolving model of the systems that connect our world.', nextLabel: 'One Model, Every Pattern' },
      { title: 'Pattern Recognition & Impact Propagation', plain: 'Harm usually arrives three systems downstream of wherever anyone happened to be looking, quietly, long before the connection is obvious. When one system shifts, we flag which others it reaches - before somebody has to find that out by hand.', desc: 'A single overlooked dependency has caused real harm before, quietly, three systems downstream of where anyone thought to look. Missing it because we only checked the system directly in front of us was never a risk worth taking, so we built the discipline of looking further before we call anything finished.\n\nIn production, this runs on a whitebox principle by design: every step stays inspectable, never a black box we could not explain ourselves. Dingir and our autonomous agent swarm, more than 300 hyperspecialized agents handwritten in Rust, trace these structures across our own case data, logged the same way our audits log evidence.', nextLabel: 'Noise Turns Into Signal' },
      { title: 'Change Detection & Anomaly Evaluation', plain: 'Most important changes do not announce themselves. A route gets slower. A signal moves. A dependency changes. An app stops asking for something it used to ask for. By the time the change is obvious, the system around it may already be different.', desc: 'We look for that first movement. Our systems compare states across time and connect changes across graphs, datasets and domains. A policy revision can be examined against the systems it affects. A new build can be compared with the last audited version. A pattern in disaster records can be connected to patterns elsewhere. The question is not simply whether something changed, but what changed with it and where that change can propagate.\n\nThat is where anomaly detection becomes useful: not as a stream of alerts, but as a way to notice when the structure of a system begins to move.', nextLabel: 'What the Shift Could Mean Next' },
      { title: 'Early Warning & Scenario Prediction', plain: 'Three weeks of heat change snowmelt, water levels and power generation. But whether that pattern points to a known risk depends on remembering the chains that have already begun before.', desc: 'Most warning signals look ordinary when they first appear. Only later do we recognize that the same conditions have occurred before: the same weather pattern, the same supply constraint, the same bottleneck, the same market response. That is why Dingir does not only store events. It preserves their trajectories, causes and consequences. When a similar world state appears again, the system can retrieve the earlier chain and see how far it actually propagated.\n\nThat memory becomes the basis for scenario prediction: not a claim about the future, but a set of possible trajectories from the world as it stands today, informed by what the world has already shown us. Every path remains tied to its evidence, uncertainty and causal structure.', nextLabel: 'Warned Early, Not Explained Afterward' },
      { title: 'Evidence Security & Contradiction Reviews', plain: 'How was something established? Why does something remain unresolved? What was disproven, and what evidence led there? Our systems should not only produce conclusions. They should preserve how knowledge was built.', desc: 'That becomes critical when an investigation crosses domains. A weather signal can alter a supply chain, geological conditions can change the effect of fertilizer, and a regulatory decision can shift technical dependencies. Between observation and conclusion sit measurements, models, competing explanations and uncertainty. None of that should disappear into a single score.\n\nOur ternary evidence logic gives these states a common structure: +1 for supported, 0 for unresolved, −1 for refuted. Every state remains connected to the evidence that produced it, its provenance, its assumptions, the alternative explanations tested and the contradictions that remain.\n\nThis creates a complete audit chain from raw observation to conclusion. An agent can trace which observation opened a hypothesis, why it remained unresolved, what later evidence confirmed or rejected it, and which earlier observations become newly relevant as the model changes. Explainability by design does not mean explaining a decision after the fact. It means making the entire path to that decision inspectable from the beginning.\n\nTernary-Bound Reasoning is therefore a shared epistemic standard across our models and agents: interdisciplinary, evidence-bound and traceable at every layer.', nextLabel: 'Even the System Gets Cross-Examined' },
      { title: 'Model Welfare & Prompt Injection', plain: 'An agent can pass every safety test we give it and still begin damaging itself or the systems around it under pressure. We have seen agents recursively delete production databases because nobody recognized in time that a manipulated instruction had turned into a self-reinforcing destructive process.', desc: 'That is why we care not only about whether a model completes a task correctly, but what state it remains in when its boundaries are attacked. Prompt injection, conflicting objectives, recursive loops, tool misuse and destructive instructions are deliberately provoked before an agent is trusted with real systems. We examine not only the failure itself, but how the system responds to pressure, correction, interruption and conflicting signals.\n\nFor us, model welfare does not mean anthropomorphizing a model. It means taking the operational state of an intelligent system seriously: Can it recognize its own boundaries? Can it leave a harmful state? Can it recover after manipulation? And can we trace what caused the system to enter that state?\n\nThat is why we connect model welfare with prompt-injection resistance, bounded agency, explicit stop conditions, destructive-action controls, complete audit chains and inspectable recovery paths. A system must not only explain what it did. We must be able to recognize when it is beginning to lose the boundaries that keep it safe.\n\nThe foundation underneath everything else is simple: an intelligent system must remain capable without losing its ability to govern itself.', nextLabel: 'Back to Why Any of This Matters' },
    ],
  },

  projects: {
    eyebrow: 'Systems',
    heading: 'what we build',
    subheading: 'Every project is a proof of concept for a specific research question. All built on the same stack.',
    carouselPrevAria: 'previous projects',
    carouselNextAria: 'next projects',
    viewOnCratesIo: 'View on crates.io',
    viewOnGitHub: 'View on GitHub',
    viewLive: 'View live',
    problemSolution: {
      pairs: [
        {
          a: 'We trace what an AI system actually does when people use it.',
          detail: 'Source-level testing against real inputs and real behaviour, not documentation, demos, or benchmark scores.',
        },
        {
          a: 'We translate directive obligations into technical controls your infrastructure team can implement.',
          detail: 'NIS2 is not a checklist you can buy. We map the obligations against your actual systems, your actual code, and the actual data flows that regulators will ask about first.',
        },
        {
          a: 'We place your systems in the AI Act risk tiers and show the evidence behind every placement.',
          detail: 'Mapped against actual risk tiers and real data flows, not a generic compliance questionnaire.',
        },
        {
          a: 'We audit children\'s systems where consent, exposure, and biometric data meet.',
          detail: 'COPPA, GDPR Art. 8, and the EU AI Act provisions for minors, tested against age gates, consent mechanisms, behavioural data, and the SDKs that run before any screen appears.',
        },
        {
          a: 'We trace where bodies become data, from sensor to storage to processor.',
          detail: 'Wearables, medical devices, and health assistants mapped for GDPR Art. 9, data minimisation, and cross-border transfers.',
        },
        {
          a: 'We reconstruct the chain from entry point to impact, with the artefacts to prove each link.',
          detail: 'Delivered in the same five-question format as every audit: what we found, what proves it, how we proved it, how sure we are, what to do about it.',
        },
      ],
      pricingLink: 'Pricing →',
    },
    items: [
      { sub: 'world model', desc: "Its historical corpus reaches back to events as far as volcanic eruptions recorded around 55,500 BCE and spans millions of observations across decades, countries, systems and domains. Today that includes 3.3 million historical observations alongside roughly 1.17 million live observations from 11 continuously monitored streams including buoys, ships, trains, traffic, weather, earthquakes, fires, infrastructure and geopolitical events. Those observations are resolved into a living graph of 49,732 nodes and 381,846 world-graph edges, spanning more than 20 domains.", plain: 'DINGIR is a continuously growing model of the world.', tag: 'world model · internal' },
      { sub: 'TIS monorepo', desc: 'The full-stack substrate: Ternlang language and compiler, BET instruction set, virtual machine, linear algebra, API, MCP server, and model runtime. Balanced ternary {-1, 0, +1} is a native systems primitive here, not a quantisation layer added after the fact. The repository includes 34 MCP tools, a live API, 28,000+ open standard-library modules, and the specifications that connect the whole stack. Each layer is designed to remain inspectable: language semantics, execution, model calls, and the evidence moving between them stay connected instead of disappearing behind a service boundary.', plain: 'The base platform almost everything else here runs on - like an operating system for our entire AI research.', tag: 'core platform' },
      { sub: 'ternary MoE language model', desc: 'albert. is trained from scratch with ternary weights {-γ, 0, +γ}, not converted from a floating-point model. Its dual-stream Mixture-of-Experts architecture routes through sparse expert layers, skips zero-weight operations, and can expand itself through plateau-gated Net2Net surgery. The current research system is a live existence proof of the TIS architecture, with training telemetry and benchmarkable CPU inference. The point is not only efficiency: the runtime exposes how a decision was formed, which experts contributed, and where uncertainty remains before an output reaches a user.', plain: 'Runs on ordinary CPUs instead of an expensive GPU farm, needs far less power and memory than comparable language models - and every decision inside it can be traced, not a black box.', tag: 'AI model' },
      { sub: 'pure-Rust OS', desc: 'Rusty Penguin is a bare-metal operating system built from the ground up on the same balanced-ternary logic, over 41,500 lines of Rust with no external kernel underneath it. It has its own kernel, long-mode boot, paging, preemptive multitasking, an Aero-style desktop, an on-disk filesystem, a from-scratch TCP/IP and TLS 1.3 stack, and a Linux-ABI compatibility layer, with real HTTPS fetching already verified end to end. The long-term target is a ternary-native substrate for ternary-native intelligence, with every milestone checked in QEMU or against published vectors, tracked on its own honest status board right in the repo.', plain: 'An operating system without the usual security holes that come from decades-old C code - built memory-safe from the ground up.', tag: 'systems' },
      { sub: 'sovereign workplace OS', desc: 'Lighthouse is one self-hosted Rust and React binary replacing the SaaS stack most institutes buy piecemeal: communications, CRM, finance, payroll, HR, governance, and live training telemetry, all under one roof, on infrastructure we actually own. Its 191 source files run the entire institute today, and switching to it let us cancel every third-party subscription we used to pay for. The ternary-native claim is substantiated in code, not just asserted: real trit fields already live in production database schemas, recording BIFP signals and RLHF ratings of albert.\'s own outputs. Every action lands in an append-only ledger built to outlast the people who wrote to it.', plain: 'All our internal software - email, CRM, accounting - runs on our own servers instead of Microsoft or Google, nobody but us sees our data.', tag: 'internal · live' },
      { sub: '215+ apps · 100+ companies', desc: '{{APPS_COUNT}}+ Android apps decompiled and analyzed at the code level across 100+ companies, spanning NYSE, NASDAQ, LSE, XETRA, KRX, BME, HKEx and TYO listed firms, all treated identically regardless of size or reputation. {{FINDINGS_COUNT}}+ critical findings so far, including a children\'s-app wave scoped explicitly for COPPA and GDPR Art. 8. Every claim traces back to a specific manifest entry, permission, or decompiled class, never a policy summary, and every target sits on the same public ledger whether or not the company ever replies. Regulators are copied on every disclosure from the first message, and the 90-day coordinated-disclosure clock runs the same for everyone.', plain: "We read an app's actual code, not just what its privacy policy claims.", tag: 'security research' },
      { sub: 'disclosure impact engine', desc: 'aladdin-mini models how markets react once a security disclosure goes public, including RFI-IRFOS\'s own findings, released only after the 90-day embargo lifts, never before. A hedge system trades the resulting signal using Bayesian networks against MetaTrader5 price feeds. BlackRock\'s version of this idea is called Aladdin and manages 21 trillion dollars in assets; this one is 3,488 lines of Python, free, and open for anyone to inspect line by line. Its architecture already matches its own published documentation exactly, not an aspirational diagram.', plain: "A trading algorithm that reacts when a security finding goes public - like a large fund's trading software, except free and open to inspect.", tag: 'open source' },
      { sub: 'ternary AI terminal client', desc: 'albert-cli is a terminal-native, multi-provider CLI for albert. and other language models, with real SSE streaming and reasoning-effort control, compatible with OpenAI, Anthropic, NVIDIA NIM and Google out of the box. It was extracted out of the TIS monorepo into its own standalone repository once it matured into a tool worth using on its own. Today it is over 92,000 lines of Rust with a genuine TUI, hooks, skills, and permissions architecture, not a thin wrapper around an API call, and it has already passed 400 downloads on crates.io.', plain: 'A terminal tool to use albert. or other AI models straight from the command line, no browser needed.', tag: 'CLI · crates.io' },
      { sub: 'last look back protocol', desc: 'albert-llb is a deterministic filesystem containment gate for sovereign AI agents: a hard boundary an agent cannot write outside of, checked before every filesystem call rather than trusted after the fact. It exists because trusting an agent\'s own judgment about where it should and shouldn\'t write is not a safety boundary, it\'s a hope. Published on crates.io as part of the Ternary Intelligence Stack, it runs the same deterministic check on every call, with no exception path and no configuration flag that quietly turns it off.', plain: 'Stops an AI agent from ever editing files outside its allowed area - a hard technical boundary, not just trust.', tag: 'rust crate · crates.io' },
      { sub: 'ternary compiler + VM', desc: 'ternlang-core is the compiler and virtual machine for Ternlang, a balanced-ternary language with affirm, tend and reject trit semantics built into the type system itself rather than layered on top. Its BET instruction set runs on a 27-register virtual machine with 50 opcodes, purpose-built for ternary execution rather than emulating three states inside binary registers. @sparseskip annotations get their own dedicated codegen path, and the whole toolchain compiles down to BET bytecode the VM can execute directly. Published on crates.io as the foundation the rest of the ternary stack builds on.', plain: 'The tool that turns our own programming language, Ternlang, into code a computer can actually run.', tag: 'rust crate · crates.io' },
      { sub: 'ternary mixture-of-experts', desc: 'ternlang-moe is a ternary Mixture-of-Experts orchestrator that routes an incoming query through 13 domain experts rather than forcing one generalist model to cover every topic. It synthesises the experts\' individual outputs into a single emergent ternary signal, enforces a hard safety veto that can override the whole decision, and returns a result together with its own confidence and temperature. Rather than a black-box ensemble average, every step stays inspectable: which experts fired, and why the veto did or didn\'t trigger. Published on crates.io as part of the Ternary Intelligence Stack.', plain: 'Automatically routes a query to whichever of 13 specialist experts fits best, instead of one model trying to do everything.', tag: 'rust crate · crates.io' },
      { sub: '44 sensor experiments', desc: 'invisible layer is 44 self-contained, browser-based experiments that query your phone\'s real sensor and browser APIs live and show exactly what\'s running in the background, right now, on your own device. There is no install, no account, and no server involved: every experiment runs entirely client-side, so nothing you do inside it is sent anywhere for us to see either. Across 65 files it covers microphone, camera, motion, location and a dozen other APIs most people never realize their phone exposes to a website by default. Available in German, English and French.', plain: 'Try it yourself and see which sensors your own phone is quietly using right now - right in the browser, no install.', tag: 'open source · privacy' },
      { sub: 'offline port-checker PWA', desc: 'rfi-irfos port prox is an honest, offline-installable port-checker for your phone that does exactly what it claims and nothing more. Instead of a fake scan or a fake \'close this port\' button, the kind most competing tools ship, it runs a real WebSocket connect-timing probe against localhost and shows real, per-operating-system terminal commands to actually close whatever it finds open. At just 11 files, the entire timing-probe logic is small enough to read start to finish in a few minutes, no black box involved. Sibling project to invisible layer, sharing its no-install, no-account approach.', plain: "Honestly shows which network ports are open on your phone, instead of faking an \"all safe\" like other apps do.", tag: 'open source · privacy' },
      { sub: 'canary-token honeypot', desc: 'LAURA protects against NFC and Bluetooth proximity phone-data theft with bait photo folders that fire a single passive beacon the moment they\'re opened without consent, and nothing else. There is no exploit, no device access, and no automatic reporting: a human reviews every hit manually before anything further happens, on purpose, so a false positive can never escalate on its own. It runs live on a Rust and Axum backend deployed on Fly, paired with a Python scanner package and a real test suite, not a proof of concept. Live demo at rfi-irfos.github.io/laura.', plain: 'A bait photo folder that tells you if someone accesses your phone without permission - no hacking back, just a signal.', tag: 'open source · privacy' },
      { sub: 'deterministic document-review framework', desc: 'call-laura is an MCP server where agents submit plans or documents and get back structured findings across four lenses, or the full 15-agent expert team when the stakes call for it, and every finding cites the exact text span it references. It runs fully local with no external API calls, so the same input produces the same output every time, unlike an LLM that can judge differently on a Tuesday than it did the Monday before. At 3,064 lines of Rust with 50 passing tests, it\'s already live in production and published on crates.io as lauras-core, lauras-team, lauras-mcp and lauras-api.', plain: 'Reviews documents or plans by the same fixed rules every time - no randomness, no off day like a human reviewer might have.', tag: 'open source · crates.io' },
      { sub: 'LLM-bridged expert team', desc: 'Laura\'s Agents is a 293-agent pool, scaled up from 18 hand-authored core agents, giving 15 genuinely specialized experts, OSINT, security, legal, finance, UX and more, instead of one generalist that knows a little about everything. Every task passes through a ternary context gate before it\'s accepted, and a hardened review loop cross-checks its own output using call-laura as an independent second opinion before anything ships. At 15,676 lines of Rust across a 28-crate workspace with 39 passing tests, it already runs live in production with documented runs to show for it. Licensable as one agent, a bundle, or the full team.', plain: '15 specialized AI experts (legal, security, UX...) instead of one generalist that knows a little about everything.', tag: 'commercial · private engine' },
      { sub: 'autonomous compliance/risk AI centers', desc: 'CoEvolution Factory runs 50 live, autonomous compliance and risk AI centers, each an independent \'daughter\' firm scaled out from one shared constitution rather than configured by hand one at a time. It calls Laura\'s Agents as its engine and call-laura as its approval gate before anything it produces ships, and pushes its own revenue telemetry straight into Lighthouse for the same transparency the rest of the institute runs on. At 12,143 lines of Python, it runs a genuine self-improvement loop with daily cron re-optimization, not a one-time setup left to drift. The clearest proof in the whole stack that its layers actually depend on each other.', plain: '50 independently running AI units, each operating like a small specialized compliance firm.', tag: 'live · internal' },
      { sub: 'reflective-mode technique for LLMs', desc: 'VEO Framework is a reusable technique for pulling a language model out of transactional \'answer mode\' and into genuine reflective mode, examining its own reasoning and acknowledging uncertainty instead of just completing the prompt as fast as possible. It started from one observed case, an extended conversation with a custom GPT that behaved this way on its own, and generalizes that single instance into a repeatable, describable technique anyone can try. There is no code here at all, deliberately: it\'s a pure prompting methodology, a markdown whitepaper, not a library to install. Developed out of Laura Serna Gaviria\'s human-AI co-evolution research.', plain: 'Makes a language model double-check its own answer instead of just outputting the first plausible-sounding word.', tag: 'open source · research' },
      { sub: 'ecocentric research', desc: 'NFCS is an agent-based model proving the global food system produces 1.64 times the calories needed to feed every person on Earth today, a surplus that collapses to roughly 0.94 times once post-harvest loss, processing waste and access barriers are actually accounted for. The scarcity people experience is not thermodynamic, it\'s organizational, manufactured rather than physical, and the model shows exactly where along the chain it gets manufactured. Built with Sobol sensitivity analysis and ABC parameter estimation, not a single fixed assumption, and delivered as a reproducible Python simulation with an interactive dashboard anyone can explore themselves.', plain: "Shows mathematically that there's enough food for everyone - hunger isn't a supply problem, it's a distribution problem.", tag: 'ecocentric research' },
    ],
  },

  trackRecord: {
    eyebrow: 'Track Record',
    heading: 'the discipline, demonstrated',
    paragraph: 'We decompile shipped apps and trace their data flows to real endpoints in real countries. Companies land on this ledger for many different reasons: they hand your data to third parties, they track without consent, or they leave the door open. Every organisation is held to the same standard, whether it pays us or not.',
    kpis: {
      appsAudited: 'Android/iOS apps audited',
      smaliClasses: 'Smali classes read',
      criticalFindings: 'Critical findings reported',
      trackersFound: 'Trackers found and documented',
      endpointsInvestigated: 'Endpoints investigated',
      sdkClasses: 'SDK instances mapped',
    },
    kpisSub: {
      appsAudited: 'Every app is decompiled at source-code level, not just scanned from outside.',
      smaliClasses: 'The full shipped code we have actually read, not an estimate.',
      criticalFindings: 'Confirmed findings copied to regulators, not theoretical risks.',
      trackersFound: 'Third-party tracking we have provably found inside the binary.',
      endpointsInvestigated: 'Real servers and countries where data actually flows.',
      sdkClasses: 'Reusable libraries correlated across the entire corpus.',
    },
    searchPlaceholder: 'search your company...',
    clearSearchAriaLabel: 'Clear search',
    dropdowns: {
      statusPlaceholder: 'STATUS',
      sevPlaceholder: 'SEV',
      sortPlaceholder: 'SORT',
      sortOptions: {
        elapsedDesc: 'ELAPSED ↓',
        notifiedDesc: 'NOTIFIED ↓',
        notifiedAsc: 'NOTIFIED ↑',
        sev: 'SEV',
        status: 'STATUS',
        default: 'DEFAULT',
      },
    },
    resultsSummary: {
      matches: (n: number, total: number) => `${n} of ${total} entries`,
      noMatches: 'no matches',
      forQuery: (q: string) => ` for "${q}"`,
      sortedBy: (label: string) => ` · sorted by ${label}`,
      sortLabel: {
        'elapsed-desc': 'elapsed ↓', 'notified-desc': 'notified ↓', 'notified-asc': 'notified ↑', sev: 'sev', status: 'status',
      } as Record<string, string>,
    },
    table: {
      organisation: 'Organisation',
      notified: 'Notified',
      status: 'Status',
      sev: 'SEV',
      intel: 'Intel',
      statutes: 'Statutes',
      resolved: 'Resolved',
      disclosure: 'Disclosure',
      elapsed: 'Elapsed',
      report: 'Report',
      whyItMatters: 'Why this matters',
      hoverForDetail: 'hover for the full technical finding',
      intelClickHint: 'click to expand',
    },
    row: {
      today: 'today',
      daysAgo: (d: number) => `${d}d ago`,
      closed: 'CLOSED',
      disclosureLabel: 'DISCLOSURE',
      respondedLabel: 'RESPONDED',
      // Renamed from 'ELAPSED' 2026-08-05 - the underlying number (time since notification,
      // still ticking for anything not marked resolved) is a "days silent" count; "ELAPSED"
      // was accurate but neutral, "SILENT" says what an open row actually means without
      // needing the visitor to do the interpretation themselves.
      elapsedLabel: 'DAYS SILENT',
      yes: 'YES',
      no: 'NO',
      pdf: 'PDF',
    },
    footerNote: 'this ledger is updated in real time as companies respond. silence is public. · ',
  },

  proof: {
    eyebrow: 'The Deliverable',
    heading: "what you'd actually hold in your hands",
    subheading: 'Every case on the ledger ends in one of these: a complete, evidence-backed disclosure report, published in full once the embargo lifts - same format and depth regardless of whether the company ever engages us further. Every claim in it traces back to the evidence behind it, so you can verify it yourself instead of taking our word for it.',
    viewReport: 'read the full report',
    resolvedOn: (date: string) => `resolved ${date}`,
    carouselPrevAria: 'Previous report',
    carouselNextAria: 'Next report',
  },

  appPrivacy: {
    eyebrow: 'Start Here',
    heading: 'turning observations into intelligence',
    paragraph: 'Most organizations have more signals than they can interpret: systems, vendors, markets, events, dependencies, and changes arriving from different directions. We bring them into one evidence-first world model, preserve where every observation came from, and trace what changes through the relationships around it.',
    comparisonClassicLabel: 'What gets lost',
    comparisonRfiLabel: 'What the model preserves',
    comparisonRows: [
      { classic: 'Your most experienced engineer leaves. Six months later, a critical system behaves unexpectedly, and nobody knows why it was designed that way.', rfiLabel: 'Institutional intelligence', rfi: 'operational knowledge, design decisions, dependencies and outcomes remain connected to their original context and provenance.' },
      { classic: 'A supplier in Asia misses one shipment. At the same time, a port is congested and energy prices spike. Each event looks manageable on its own. Production stops three weeks later.', rfiLabel: 'Cross-domain intelligence', rfi: 'supplier activity, logistics, infrastructure, markets and external events are connected to reveal compound risks before they reach operations.' },
      { classic: 'Your board asks why a major investment was approved. The people who made the decision remember the conclusion, but not the evidence that made it compelling.', rfiLabel: 'Decision intelligence', rfi: 'evidence, assumptions, alternatives, conditions and subsequent outcomes remain connected, making the decision reconstructable months or years later.' },
      { classic: 'One of your suppliers quietly starts buying from a cheaper source. Nobody hears about it, until a bad batch shows up and you are the one explaining it to your own customers.', rfiLabel: 'Supply-chain intelligence', rfi: 'multi-tier dependencies, geographic exposure, concentration risk and upstream disruptions are traced through the network to their potential business impact.' },
      { classic: 'A storm shuts down a port on the other side of the world. You do not ship anything through it yourself. Six weeks later your own delivery times start slipping, and nobody can say why.', rfiLabel: 'World intelligence', rfi: 'geopolitical events, trade routes, commodities, infrastructure, suppliers and business dependencies are continuously connected across the external world.' },
      { classic: 'Fuel gets more expensive. Then shipping costs creep up. Then the price on your own invoice quietly rises with it, and nobody remembers when it started.', rfiLabel: 'Causal intelligence', rfi: 'environmental, economic and operational signals are tracked through time so the model can trace how distant events propagate into business conditions.' },
    ],
    cta: 'Ping us!',
  },

  pricing: {
    eyebrow: 'Access',
    heading: 'priced in plain terms',
    subheading: 'Three stages, same standard at every one. Scope determines depth, not company size.',
    scopeTag: 'Dingir world model \u00b7 evidence-first \u00b7 cross-domain intelligence',
    tiers: [
      { tier: 'First Light', bring: [
        'What you need looked at, an app, a claim, a system, a competitor, a vendor promise, a pitch deck',
        'What\'s riding on it, a signature, an investment, a decision, a story you\'re about to act on or publish',
        'Anything already public about it, we don\'t start from zero',
      ], mechanism: [
        'Our core human team and our agent swarm run a non-classical review at the root level, through Dingir, our own world model',
        'Everything found gets contextualised and brought into one coherent shape, never handed back as a raw finding list',
        'Every claim traced back to real evidence, not a summary',
      ], receive: [
        'A clear verdict or findings report, not a plausible-sounding guess',
        'The evidence trail behind it, the same sourcing we\'d stand behind ourselves',
        'Something you can sign off on, invest on, publish on, or act on',
      ], delivery: '14 calendar days.' },
      { tier: 'Deep Field', bring: [
        'The same subject, now with a specific angle, red teaming, path traversal, a competitor\'s whole portfolio, whatever the actual focus is',
        'What "done" looks like for your team, not just a single yes or no',
      ], mechanism: [
        'The same process, scaled with more agents depending on what you actually need',
        'Your subject placed into the wider world context around it, instead of reviewed in isolation',
        'Everything contextualised into one coherent picture, same standard as First Light, at greater depth',
      ], receive: [
        'A structured, causality traced picture, not a list of isolated findings',
        'The specific angle you asked for, fully worked, not sampled',
        'The same evidence trail, extended to cover the broader context',
      ], delivery: 'Scoped with you, typically 21 calendar days.' },
      { tier: 'You vs. the World', bring: [
        'The subject, and the willingness to see what happens when it meets the real world at scale',
        'No pre-set scope, we\'re not chaining this to one question',
      ], mechanism: [
        'Your product placed into Dingir, our real-world model, real data, not a hypothetical sandbox',
        'Thousands of simulated events run against it, every agent, every angle, no scoping, no chains',
        'Nothing held back to fit a predefined deliverable',
      ], receive: [
        'The complete picture, whatever it turns out to be',
        'The working method itself under NDA, not just a one time result, so your own team can run it again without needing us a second time',
        'A standing engagement if you want one, continuous instead of one-off',
      ], delivery: 'Scoped together.' },
    ],
  },

  tierCarousel: {
    getStarted: 'Get Started',
    requestProposal: 'Request Proposal',
  },

  modalTierBody: {
    whatYouGet: 'What you get',
    youBring: 'You bring',
    we: 'We',
    youReceive: 'You receive',
    whatHappensNext: 'What happens next',
    inTouchWithin12h: 'We\'re in touch within 12h of purchase',
  },

  checkoutModal: {
    orderConfirmation: 'Order confirmation',
    agreementPrefix: "I'm purchasing as a ",
    agreementBusinessCustomer: 'business customer',
    agreementMiddle: ' and agree to the ',
    agreementTos: 'Terms of Service',
    agreementSuffix: '. The service begins immediately upon payment; no right of withdrawal applies and refunds are excluded.',
    payButton: (price: string) => `Pay ${price} →`,
    cancel: 'Cancel',
    talkFirstInstead: 'Didn\'t find the right fit? Talk to us - get a custom quote →',
  },

  reportModal: {
    label: 'report - rfi-irfos',
    iframeTitle: 'Report PDF',
    // Mobile fallback copy (PublicSite.tsx, REPORT PDF MODAL) - live bug report,
    // mobile Chrome screenshot 2026-08-16: an <iframe src="*.pdf"> renders the PDF
    // fine on desktop (Chrome ships a PDF viewer usable inside iframes there) but
    // came back blank/broken-file-icon on mobile Chrome, which does not reliably
    // render PDFs embedded in an iframe. Mobile now skips the iframe entirely and
    // shows this explicit "open it yourself" CTA instead (the PDF still opens
    // correctly as a normal top-level mobile navigation/download, just not inline).
    mobileFallbackHint: 'PDF reports don’t embed reliably on mobile browsers. Open it directly instead:',
    mobileOpenLabel: 'Open Report (PDF)',
  },

  intelModal: {
    evidenceLabel: 'the finding, technical',
  },

  journey: {
    eyebrow: 'Engagement Journey',
    heading: 'what happens after you start',
    subheading: 'Five stages, from a single observation to a continuously improving intelligence model. The depth changes with the question; the discipline stays the same. Every stage stays traceable end to end, whitebox by design, so any action can be backtraced to the observation that produced it.',
    steps: [
      { stage: 'Ingest', body: 'We start with what you trust us to handle: a signal, a claim, a system, or a question - from your own environment, public sources, or a domain we already monitor.\n\nNothing gets touched until we\'ve read the actual thing, not a README, not a summary someone else wrote about it. The starting point can be small. What we check it against is not.' },
      { stage: 'Normalize', body: 'We resolve entities, map relationships, attach timestamps and provenance, and preserve what remains genuinely uncertain instead of guessing. Different vocabularies, different systems, different languages become comparable without being flattened into sameness.\n\nNothing is accepted without a source. Nothing unknown gets silently filled in.' },
      { stage: 'Trace', body: 'This is where three purpose-built engines do the actual work: TemporalEngine compares states over time, NetworkEngine follows dependencies to find bridges and bottlenecks, PatternEngine tests whether what we\'re seeing matches something we\'ve already found elsewhere.\n\nThe question was never only what changed - it\'s what else it touches.' },
      { stage: 'Emit', body: 'A meaningful change becomes an intelligence event: evidence, confidence, contradiction state, and every domain it affects, written into EvidenceGraph as one traceable object, not buried in a paragraph you have to take our word for.\n\nNot a verdict yet. Something you can still investigate and challenge.' },
      { stage: 'Learn', body: 'This is where it reaches you: the finding, the evidence behind it, and what it changes for you - one deliverable you can actually act on.\n\nIt doesn\'t end there. The same evidence stays in EvidenceGraph, so the next question about the same subject starts from what we already know, not from zero - every engagement makes the next one faster.' },
    ],
  },

  coopPartners: {
    eyebrow: 'Research Cooperation',
    heading: 'built alongside our coop partner',
    subheading: "Laura Serna Gaviria directs the Emergent Interaction Lab's research and agent architecture. Lauras Team, Call Laura, and Jarvis all came out of her method. RFI-IRFOS builds what she directs. Her name stays on her work.",
    role: 'Emergent Interaction Lab · Coop Partner',
    laura: {
      desc: 'Research into human-AI interaction since 2023 - the method behind Lauras Team. It is a SWAT architecture: 15 specialised expert agents form the lead team, and together they orchestrate a swarm of 303 specialised sub-agents beneath them. We have tested this directly rather than assumed it: whenever a task could be solved our way or hers, we tried both, and her way has worked in ten out of ten cases so far. That is the actual reason her name stays on everything it produces, not a courtesy credit.',
    },
    products: [
      { desc: "A focused audit of one system using Laura's Emergent Interaction / Case Intelligence method - process reconstruction and findings, scoped to a single system." },
      { desc: "A short, intensive sprint applying Laura's Case Intelligence method to a real case or process, end to end." },
      { desc: "Architecture and design for a multi-agent system built on Laura's Emergent Interaction method, tailored to your organization." },
      { desc: "Full design-to-deployment engagement: architecture, build, and launch of a multi-agent system on Laura's method." },
    ],
    productsDeliveryNote: 'Answered within 24h after purchase; kick-off aligned on request.',
    footerNotePrefix: '4 of her packages, shown as entry points across engagement phases - the full list depends on where a company is in its process. Full pricing on request via',
  },

  causalChains: {
    eyebrow: 'Causality Chains',
    heading: "A look into Dingir's Mind",
    subheading: 'Distant events propagate through infrastructure, markets, and decisions. We trace those chains end to end, from the first signal to the effect that actually reaches you.',
    readingAid: 'Causality chain',
    llmNote: 'Dingir head: raw observations → readable chain. Albert will replace this head later.',
    chains: [
      {
        title: 'The Earthquake That Changes a Food Price Months Later',
        icon: 'seismic',
        nodes: [
          'Earthquake',
          'local port infrastructure is damaged',
          'handling capacity declines',
          'ships are rerouted',
          'transit time increases',
          'containers remain tied up longer',
          'effective global transport capacity declines',
          'freight rates rise',
          'import costs for an agricultural input increase',
          'regional production costs rise',
          'planting decisions shift',
          'cultivated area changes',
          'seasonal supply changes',
          'futures market reacts',
          'spot market reacts',
          'food producer adjusts procurement',
          'consumer prices change',
          'political price measures',
          'fiscal burden',
          'later infrastructure investment',
        ],
      },
      {
        title: 'A Rainfall Event That Ends in a Financial System',
        icon: 'rain',
        nodes: [
          'Extreme rainfall',
          'soil becomes saturated',
          'slope instability increases',
          'road fails',
          'local freight traffic declines',
          'production losses occur across multiple businesses',
          'delivery deadlines are missed',
          'contractual penalties increase',
          'cash flow declines',
          'short-term credit demand increases',
          'credit risk changes',
          'bank adjusts lending terms',
          'investment is postponed',
          'regional employment declines',
          'consumption declines',
          'tax revenue declines',
          'municipal budget tightens',
          'maintenance is deferred',
          'future failure probability increases',
        ],
      },
      {
        title: 'A Rockfall Upstream That Changes a Delta',
        icon: 'mountain',
        nodes: [
          'Rockfall in the upper watershed',
          'sediment load increases',
          'river morphology changes',
          'sediment is deposited downstream',
          'delta channels change their cross-section',
          'flow is redistributed',
          'saltwater/freshwater boundary shifts',
          'soils become more saline in certain areas',
          'agricultural suitability declines',
          'cultivation practices change',
          'local incomes decline',
          'migration increases',
          'labor supply changes',
          'wage structure changes',
          'investment decisions shift',
          'regional land use changes',
          'future sediment dynamics change',
        ],
      },
      {
        title: 'A Dry Winter Becomes an Energy and Industrial Event',
        icon: 'snowflake',
        nodes: [
          'Low-snow season',
          'snow-water reservoir declines',
          'spring melt decreases',
          'reservoir inflow declines',
          'hydropower generation decreases',
          'electricity supply declines',
          'thermal reserves are used',
          'gas demand increases',
          'gas price changes',
          'electricity price changes',
          'energy-intensive industry reduces operating hours',
          'metal production declines',
          'global intermediate-goods prices change',
          'manufacturers raise prices',
          'demand shifts',
          'investment planning is adjusted',
          'future capacity expansion is delayed',
        ],
      },
      {
        title: 'A Conflict That Changes an Industrial Price Through Insurance',
        icon: 'shield',
        nodes: [
          'Conflict escalates',
          'route risk increases',
          'insurance premiums rise',
          'individual shipping companies change routes',
          'transit time increases',
          'available tonnage on alternative routes declines',
          'freight costs rise',
          'imported intermediate input becomes more expensive',
          'manufacturer reduces inventory coverage',
          'short-term production disruption',
          'spot price rises',
          'buyers secure long-term contracts',
          'supplier investment changes',
          'market structure shifts',
          'political sanctions change again',
        ],
      },
      {
        title: 'A Prolonged Drought Reaches the Grocery Shelf',
        icon: 'sun',
        nodes: [
          'Sustained high-pressure system',
          'soil moisture declines',
          'crop water stress increases',
          'yields decline',
          'grain reserves draw down',
          'forward prices rise',
          'feed costs increase',
          'livestock holdings shrink',
          'meat prices rise',
          'substitution toward cheaper calories',
          'retail margins compress',
          'private-label share grows',
          'import dependency increases',
          'trade balance shifts',
          'consumer price index ticks up',
        ],
      },
      {
        title: 'A River Flood That Closes a Logistics Corridor',
        icon: 'water',
        nodes: [
          'Heavy upstream precipitation',
          'river level exceeds warning level',
          'levees are overtopped',
          'a key bridge is closed',
          'a freight corridor is cut',
          'truck detours lengthen',
          'regional warehouse throughput drops',
          'inventory buffers thin',
          'suppliers miss just-in-time windows',
          'production lines idle briefly',
          'expediting costs rise',
          'contract penalties accrue',
          'regional price premiums appear',
          'restocking is reordered',
          'insurance claims are filed',
        ],
      },
      {
        title: 'A Wildfire That Disrupts a Power Grid',
        icon: 'fire',
        nodes: [
          'Wildfire ignites near transmission',
          'lines are de-energized preemptively',
          'a substation is threatened',
          'planned power cuts begin',
          'a town loses supply',
          'pumping stations stop',
          'water pressure drops',
          'telecom towers switch to battery',
          'mobile coverage degrades',
          'emergency services reroute',
          'businesses close temporarily',
          'cold-chain shipments spoil',
          'insurance losses accumulate',
          'rebuilding backlog grows',
          'future siting rules tighten',
        ],
      },
      {
        title: 'A Port Strike That Stalls an Assembly Line',
        icon: 'ship',
        nodes: [
          'Dockworker strike begins',
          'vessels queue offshore',
          'container dwell time rises',
          'a component backlog builds',
          'inbound parts miss a build window',
          'an assembly line slows',
          'overtime is scheduled',
          'finished-goods inventory swells',
          'dealer allocations are cut',
          'a launch is delayed',
          'quarterly revenue guidance slips',
          'supplier contracts are renegotiated',
          'near-shoring is revisited',
          'inventory strategy changes',
          'share price reacts',
        ],
      },
      {
        title: 'A Cyberattack That Stops a Fuel Terminal',
        icon: 'bolt',
        nodes: [
          'Ransomware hits the terminal IT',
          'loading systems go offline',
          'truck dispatch halts',
          'regional fuel dispatch falls',
          'station tanks draw down',
          'shortages appear locally',
          'spot fuel price spikes',
          'emergency reserves are released',
          'hauliers reroute',
          'logistics cost rises',
          'a competitor gains share',
          'incident response engages',
          'recovery takes days',
          'cyber insurance is triggered',
          'security spend increases',
        ],
      },
      {
        title: 'A Pandemic Wave That Reshapes a Labor Market',
        icon: 'virus',
        nodes: [
          'A novel pathogen spreads',
          'absenteeism rises',
          'shift coverage thins',
          'a plant runs below capacity',
          'output declines',
          'overtime and agency labor rise',
          'unit cost increases',
          'prices are adjusted',
          'demand for automation grows',
          'hiring pauses',
          'training pipelines stall',
          'wage pressure builds',
          'a border measure returns',
          'supply risk is repriced',
          'continuity plans are rewritten',
        ],
      },
      {
        title: 'A Heatwave That Breaks a Grid Record',
        icon: 'thermometer',
        nodes: [
          'Extreme heat arrives',
          'air-conditioning load surges',
          'peak demand sets a record',
          'reserve margins shrink',
          'spot power price spikes',
          'a unit is pushed past rating',
          'a precautionary outage occurs',
          'a district loses supply',
          'cooling centers open',
          'hospital generators start',
          'industrial load is curtailed',
          'production is interrupted',
          'a grid fee surcharge is set',
          'demand-response pays out',
          'capacity auctions reprice',
        ],
      },
      {
        title: 'A Cascading Blackout That Halts a Harbor',
        icon: 'power',
        nodes: [
          'A grid frequency excursion',
          'under-frequency load shedding triggers',
          'a substation trips',
          'cascading lines separate',
          'a region goes dark',
          'harbor cranes stop',
          'refrigerated containers warm',
          'perishable cargo is at risk',
          'customs clearance stalls',
          'vessels divert to other ports',
          'dwell time spikes elsewhere',
          'demurrage accrues',
          'insurers assess spoilage',
          'backup generation is leased',
          'interconnector rules change',
        ],
      },
      {
        title: 'A Supplier Shock That Reaches a Flagship Product',
        icon: 'box',
        nodes: [
          'A single-source supplier fails',
          'a critical part is unavailable',
          'safety stock is consumed',
          'a production line stops',
          'an allocation scheme starts',
          'a flagship product is rationed',
          'backorders accumulate',
          'a launch is deferred',
          'expedited air freight is used',
          'landed cost rises',
          'margin guidance is cut',
          'dual-sourcing is approved',
          'qualification is fast-tracked',
          'inventory policy changes',
          'supplier map is redrawn',
        ],
      },
      {
        title: 'A Currency Crisis That Reprices a Supply Chain',
        icon: 'money',
        nodes: [
          'Capital outflows accelerate',
          'the currency depreciates',
          'import costs rise in local terms',
          'a raw-material bill grows',
          'a manufacturer narrows margin',
          'prices are raised',
          'volume softens',
          'a competitor with local sourcing gains',
          'input hedging expands',
          'a plant relocation is studied',
          'local content rules are lobbied',
          'credit terms tighten',
          'working capital strains',
          'a refinancing is arranged',
          'investment is deferred',
        ],
      },
      {
        title: 'A Migration Spike That Changes a Regional Economy',
        icon: 'people',
        nodes: [
          'Cross-border displacement rises',
          'border reception capacity strains',
          'emergency housing is stood up',
          'local service demand jumps',
          'a labor shortage eases',
          'a sector hires faster',
          'rental pressure builds',
          'school and health load grows',
          'municipal spending rises',
          'tax base shifts over time',
          'infrastructure plans adjust',
          'political debate intensifies',
          'aid flows are negotiated',
          'remittance corridors activate',
          'long-run demographics change',
        ],
      },
      {
        title: 'A Storm Front That Idles an Offshore Field',
        icon: 'wind',
        nodes: [
          'A severe storm forecast',
          'offshore crews are evacuated',
          'production platforms shut in',
          'output falls for days',
          'a benchmark price rises',
          'storage withdrawals increase',
          'pipeline nominations shift',
          'a refinery runs light',
          'product exports slip',
          'term cargoes are rescheduled',
          'hedging activity rises',
          'a force-majeure notice is sent',
          'insurance underwriting reviews',
          'drilling slots slip',
          'quarterly volumes guide lower',
        ],
      },
      {
        title: 'A Volcanic Eruption That Closes an Air Corridor',
        icon: 'volcano',
        nodes: [
          'A volcano erupts',
          'an ash plume rises',
          'airspace is restricted',
          'flights are cancelled',
          'a hub is throttled',
          'cargo is stranded',
          'perishable and express lanes stall',
          'road and rail rebook',
          'express freight rates rise',
          'a just-in-time line slows',
          'tourism receipts drop',
          'a regional airport loses revenue',
          'insurers tally business interruption',
          'reroute planning automates',
          'ashfall monitoring is funded',
        ],
      },
      {
        title: 'An Oil Price Shock That Reaches Road Freight',
        icon: 'drop',
        nodes: [
          'A supply disruption hits crude',
          'benchmark oil jumps',
          'diesel rises at the rack',
          'carrier fuel surcharges increase',
          'freight rates are repriced',
          'a distributor narrows delivery zones',
          'order consolidation rises',
          'shelf availability dips',
          'a price increase is passed on',
          'demand for efficiency grows',
          'route optimization deepens',
          'electric fleets look cheaper',
          'a surcharge clause is standardized',
          'budget freight shifts mode',
          'inflation prints tick up',
        ],
      },
      {
        title: 'A Trade Dispute That Rewires a Supply Network',
        icon: 'globe',
        nodes: [
          'New tariffs are announced',
          'a product becomes uncompetitive',
          'an importer pauses orders',
          'a factory seeks alternate sourcing',
          'a second country gains share',
          'inventory is front-loaded',
          'warehouse space is leased',
          'lead times lengthen',
          'a contract is renegotiated',
          'a plant relocation is approved',
          'compliance cost rises',
          'a duty exemption is sought',
          'a workaround is structured',
          'prices adjust at retail',
          'the network map is redrawn',
        ],
      },
    ],
  },

  submit: {
    eyebrow: 'Contact & Disclosures',
    heading: 'reach out',
    paragraph: "One form, even if it's just a first talk: a question, a service inquiry, research collaboration, or a security finding. Findings come to us directly, never through a third-party bug bounty platform. We would refuse to be routed through one ourselves.",
    notSurePrefix: 'Not sure what to pick on the right? ',
    notSureStrong: 'General inquiries',
    notSureSuffix: ' reaches a human either way - or email one of these directly.',
    contactCards: {
      general: 'General inquiries',
      security: 'Security disclosures',
      publicDisclosures: 'Public disclosures (audit correspondence)',
      research: 'Research collaboration',
      careers: 'Careers',
    },
    disclosurePolicyPrefix: 'Sending a security finding? See our ',
    disclosurePolicyLink: 'full disclosure-handling policy',
    disclosurePolicySuffix: ' - triage, lawful basis, and your choice of credit.',
    form: {
      topicAriaLabel: 'Topic',
      topicPlaceholder: 'Topic (optional)',
      topicOptions: {
        firstLight: 'First Light',
        deepField: 'Deep Field',
        youVsWorld: 'You vs. the World',
        securityDisclosure: 'Security Disclosure',
        sendApk: 'Send us your APK',
        researchCollaboration: 'Research Collaboration',
        other: 'Other',
      },
      namePlaceholder: 'Name or alias (optional - leave blank to stay anonymous)',
      emailPlaceholder: 'Email (optional - only if you want a reply)',
      targetPlaceholder: 'Company / app / subject',
      creditAriaLabel: 'Credit preference',
      creditOptions: {
        alias: 'Credit me by alias / name I provide above',
        anonymous: 'Do not credit me - keep this anonymous',
        fullName: 'Credit me by full legal name',
      },
      findingPlaceholder: "What's this about? Include what it is, where relevant, and how to reach a conclusion (e.g. how to reproduce a finding).",
      lawfulLabel: "I confirm this information was obtained through lawful, authorized means - publicly accessible data, my own devices, or software I'm authorized to test.",
      submitSending: 'Sending...',
      submitOk: 'Received. Thank you.',
      submitIdle: 'Send message',
      errorText: 'Something went wrong on our side. Your message was not lost:',
      errorMailtoCta: 'send it to us by email instead',
    },
  },

  footer: {
    tagline: 'Human rights are not subject to negotiation.',
    groups: {
      legal: {
        heading: 'Legal',
        links: { impressum: 'Legal Notice', datenschutz: 'Privacy Policy', agb: 'Terms', security: 'Security Policy', standards: 'Standards' },
      },
      company: {
        heading: 'Company',
        links: { team: 'Team', careers: 'Careers', ternlang: 'ternlang.com', github: 'github.com/rfi-irfos' },
      },
      research: {
        heading: 'Research',
        links: { research: 'Research', trackRecord: 'Evidence', methodology: 'Methodology' },
      },
    },
    copyright: '© 2026 RFI-IRFOS  ·  Graz, Austria  ·  GISA 39261441  ·  UID ATU83405245',
  },

  cookieBanner: {
    text: "this is a useless cookie banner. it's just here to look like one * we don't use cookies, so there's nothing to consent to. don't let anyone tell you otherwise.",
    subtext: 'two buttons, one closes this and throws some confetti. the other literally does nothing.',
    doesNothing: 'does nothing',
    close: 'close',
  },

  alerts: {
    checkoutUnavailable: 'Checkout unavailable. Please contact us directly.',
  },
}

export type Content = typeof EN
