// Footer repo directory data (live feedback 2026-08-14, relayed from Laura via
// Simeon: "wir sollten wie alle unsere arbeit da rein tun"). Snapshot of public
// repos only - a linked private repo 404s for any visitor who isn't a
// collaborator, which reads as broken, not thorough. Pulled via `gh repo list
// <org|user> --json name,isPrivate,url` on 2026-08-14; a static snapshot, not a
// live fetch (this is a prerendered static site - no client-side GitHub API call
// on every page load, and no risk of hitting GitHub's unauthenticated rate limit
// for visitors). Will drift as repos are added/renamed; re-pull periodically
// rather than trying to keep this perfectly in sync.
export const RFI_REPOS: { n: string; u: string }[] = [
  { n: '.github', u: 'https://github.com/rfi-irfos/.github' },
  { n: '13', u: 'https://github.com/rfi-irfos/13' },
  { n: 'agent-albert-cli', u: 'https://github.com/rfi-irfos/agent-albert-cli' },
  { n: 'aladdin-mini', u: 'https://github.com/rfi-irfos/aladdin-mini' },
  { n: 'albert-spores', u: 'https://github.com/rfi-irfos/albert-spores' },
  { n: 'auto-bayesian', u: 'https://github.com/rfi-irfos/auto-bayesian' },
  { n: 'autoguardrails', u: 'https://github.com/rfi-irfos/autoguardrails' },
  { n: 'bifp', u: 'https://github.com/rfi-irfos/bifp' },
  { n: 'call-laura', u: 'https://github.com/rfi-irfos/call-laura' },
  { n: 'causal-perception-implementation', u: 'https://github.com/rfi-irfos/causal-perception-implementation' },
  { n: 'coevolution-factory', u: 'https://github.com/rfi-irfos/coevolution-factory' },
  { n: 'e-techbike-at', u: 'https://github.com/rfi-irfos/e-techbike-at' },
  { n: 'emergent-interaction-lab', u: 'https://github.com/rfi-irfos/emergent-interaction-lab' },
  { n: 'foodchain-analysis', u: 'https://github.com/rfi-irfos/foodchain-analysis' },
  { n: 'gen-fraud-graph', u: 'https://github.com/rfi-irfos/gen-fraud-graph' },
  { n: 'genesis', u: 'https://github.com/rfi-irfos/genesis' },
  { n: 'genetic-algorithm', u: 'https://github.com/rfi-irfos/genetic-algorithm' },
  { n: 'ginie', u: 'https://github.com/rfi-irfos/ginie' },
  { n: 'invisible-layer', u: 'https://github.com/rfi-irfos/invisible-layer' },
  { n: 'laura', u: 'https://github.com/rfi-irfos/laura' },
  { n: 'lauras-agents-public', u: 'https://github.com/rfi-irfos/lauras-agents-public' },
  { n: 'lauras-port-proxy', u: 'https://github.com/rfi-irfos/lauras-port-proxy' },
  { n: 'linear-adapter-trainer', u: 'https://github.com/rfi-irfos/linear-adapter-trainer' },
  { n: 'llm_bridge', u: 'https://github.com/rfi-irfos/llm_bridge' },
  { n: 'mech-gov-framework', u: 'https://github.com/rfi-irfos/mech-gov-framework' },
  { n: 'mutatis-mutandis', u: 'https://github.com/rfi-irfos/mutatis-mutandis' },
  { n: 'nikoletta-tutor', u: 'https://github.com/rfi-irfos/nikoletta-tutor' },
  { n: 'ntpsec', u: 'https://github.com/rfi-irfos/ntpsec' },
  { n: 'p2p-repository', u: 'https://github.com/rfi-irfos/p2p-repository' },
  { n: 'ralph', u: 'https://github.com/rfi-irfos/ralph' },
  { n: 'ralph-vault-skill', u: 'https://github.com/rfi-irfos/ralph-vault-skill' },
  { n: 'rfi-irfos-web', u: 'https://github.com/rfi-irfos/rfi-irfos-web' },
  { n: 'rusty-penguin', u: 'https://github.com/rfi-irfos/rusty-penguin' },
  { n: 'RuVector', u: 'https://github.com/rfi-irfos/RuVector' },
  { n: 'sota-stressed-datasets', u: 'https://github.com/rfi-irfos/sota-stressed-datasets' },
  { n: 'ternary-intelligence-stack', u: 'https://github.com/rfi-irfos/ternary-intelligence-stack' },
  { n: 'ternary-intelligence-stack-genesis-archive', u: 'https://github.com/rfi-irfos/ternary-intelligence-stack-genesis-archive' },
  { n: 'veo-framework', u: 'https://github.com/rfi-irfos/veo-framework' },
]

export const SIMEON_REPOS: { n: string; u: string }[] = [
  { n: 'abliterator', u: 'https://github.com/simeon-kepp/abliterator' },
  { n: 'albert-strategy-orchestrator', u: 'https://github.com/simeon-kepp/albert-strategy-orchestrator' },
  { n: 'ansible', u: 'https://github.com/simeon-kepp/ansible' },
  { n: 'api-guidelines', u: 'https://github.com/simeon-kepp/api-guidelines' },
  { n: 'api-registry', u: 'https://github.com/simeon-kepp/api-registry' },
  { n: 'awesome-go', u: 'https://github.com/simeon-kepp/awesome-go' },
  { n: 'awesome-iOS-security-tools', u: 'https://github.com/simeon-kepp/awesome-iOS-security-tools' },
  { n: 'awesome-mac', u: 'https://github.com/simeon-kepp/awesome-mac' },
  { n: 'awesome-python', u: 'https://github.com/simeon-kepp/awesome-python' },
  { n: 'awesome-scalability', u: 'https://github.com/simeon-kepp/awesome-scalability' },
  { n: 'bazaarak', u: 'https://github.com/simeon-kepp/bazaarak' },
  { n: 'burn', u: 'https://github.com/simeon-kepp/burn' },
  { n: 'candle', u: 'https://github.com/simeon-kepp/candle' },
  { n: 'committers.top', u: 'https://github.com/simeon-kepp/committers.top' },
  { n: 'crewAI', u: 'https://github.com/simeon-kepp/crewAI' },
  { n: 'cybersecurity-SOAR', u: 'https://github.com/simeon-kepp/cybersecurity-SOAR' },
  { n: 'deutsch-lernen-pwa', u: 'https://github.com/simeon-kepp/deutsch-lernen-pwa' },
  { n: 'dynamodb-toolbox', u: 'https://github.com/simeon-kepp/dynamodb-toolbox' },
  { n: 'emergent-interaction-lab', u: 'https://github.com/simeon-kepp/emergent-interaction-lab' },
  { n: 'flax', u: 'https://github.com/simeon-kepp/flax' },
  { n: 'foodsharing', u: 'https://github.com/simeon-kepp/foodsharing' },
  { n: 'frida-ipa-extract', u: 'https://github.com/simeon-kepp/frida-ipa-extract' },
  { n: 'frida-tools', u: 'https://github.com/simeon-kepp/frida-tools' },
  { n: 'github-mcp-server', u: 'https://github.com/simeon-kepp/github-mcp-server' },
  { n: 'hermes-agent', u: 'https://github.com/simeon-kepp/hermes-agent' },
  { n: 'hermes-agent-bundle', u: 'https://github.com/simeon-kepp/hermes-agent-bundle' },
  { n: 'hermes-bundle', u: 'https://github.com/simeon-kepp/hermes-bundle' },
  { n: 'hermes-setup', u: 'https://github.com/simeon-kepp/hermes-setup' },
  { n: 'invisible-layer', u: 'https://github.com/simeon-kepp/invisible-layer' },
  { n: 'iOS-Binary-Security-Analyzer', u: 'https://github.com/simeon-kepp/iOS-Binary-Security-Analyzer' },
  { n: 'jadx', u: 'https://github.com/simeon-kepp/jadx' },
  { n: 'jupyterlab_pygments', u: 'https://github.com/simeon-kepp/jupyterlab_pygments' },
  { n: 'keras', u: 'https://github.com/simeon-kepp/keras' },
  { n: 'linguist', u: 'https://github.com/simeon-kepp/linguist' },
  { n: 'llama.cpp', u: 'https://github.com/simeon-kepp/llama.cpp' },
  { n: 'lunar-phase-calendar', u: 'https://github.com/simeon-kepp/lunar-phase-calendar' },
  { n: 'MixedRadixCircuitSynthesis', u: 'https://github.com/simeon-kepp/MixedRadixCircuitSynthesis' },
  { n: 'ML-From-Scratch', u: 'https://github.com/simeon-kepp/ML-From-Scratch' },
  { n: 'mutatis-mutandis', u: 'https://github.com/simeon-kepp/mutatis-mutandis' },
  { n: 'netron', u: 'https://github.com/simeon-kepp/netron' },
  { n: 'ntpsec', u: 'https://github.com/simeon-kepp/ntpsec' },
  { n: 'OntologyScope', u: 'https://github.com/simeon-kepp/OntologyScope' },
  { n: 'openapi-to-graphql', u: 'https://github.com/simeon-kepp/openapi-to-graphql' },
  { n: 'osiris', u: 'https://github.com/simeon-kepp/osiris' },
  { n: 'pocketbase', u: 'https://github.com/simeon-kepp/pocketbase' },
  { n: 'PowerToys', u: 'https://github.com/simeon-kepp/PowerToys' },
  { n: 'python-ternary', u: 'https://github.com/simeon-kepp/python-ternary' },
  { n: 'ResonanceFlow', u: 'https://github.com/simeon-kepp/ResonanceFlow' },
  { n: 'rfi-labs-arcade', u: 'https://github.com/simeon-kepp/rfi-labs-arcade' },
  { n: 'ruflo', u: 'https://github.com/simeon-kepp/ruflo' },
  { n: 'RuVector', u: 'https://github.com/simeon-kepp/RuVector' },
  { n: 'RuView', u: 'https://github.com/simeon-kepp/RuView' },
  { n: 'rvllm', u: 'https://github.com/simeon-kepp/rvllm' },
  { n: 'simeon-kepp', u: 'https://github.com/simeon-kepp/simeon-kepp' },
  { n: 'SoftwareSystemsEngineering', u: 'https://github.com/simeon-kepp/SoftwareSystemsEngineering' },
  { n: 'sparc', u: 'https://github.com/simeon-kepp/sparc' },
  { n: 'Synaptic-Mesh', u: 'https://github.com/simeon-kepp/Synaptic-Mesh' },
  { n: 'tensorflow', u: 'https://github.com/simeon-kepp/tensorflow' },
  { n: 'tensorzero', u: 'https://github.com/simeon-kepp/tensorzero' },
  { n: 'Termix', u: 'https://github.com/simeon-kepp/Termix' },
  { n: 'TernaryMoralLogic', u: 'https://github.com/simeon-kepp/TernaryMoralLogic' },
  { n: 'TernCore-Silicon', u: 'https://github.com/simeon-kepp/TernCore-Silicon' },
  { n: 'ternlang-stdlib', u: 'https://github.com/simeon-kepp/ternlang-stdlib' },
  { n: 'TernVector', u: 'https://github.com/simeon-kepp/TernVector' },
  { n: 'the-book-of-secret-knowledge', u: 'https://github.com/simeon-kepp/the-book-of-secret-knowledge' },
  { n: 'tinygrad', u: 'https://github.com/simeon-kepp/tinygrad' },
  { n: 'top-github-users', u: 'https://github.com/simeon-kepp/top-github-users' },
  { n: 'tree-sitter-ternlang', u: 'https://github.com/simeon-kepp/tree-sitter-ternlang' },
  { n: 'wayfinder', u: 'https://github.com/simeon-kepp/wayfinder' },
  { n: 'xlstm', u: 'https://github.com/simeon-kepp/xlstm' },
]
