// Full repo/crate directory (restored 2026-08-15, live feedback: the zone-grouped
// System Card modal in content/systems.ts covers 21 curated systems with real
// depth, but the footer should still show everything, not just the curated set -
// "alle trophies"). Rendered as a plain, dense link list below the four System
// Card zones, same "no descriptors, just the link" treatment the curated zones
// themselves settled on - full depth lives in the modal for the 21 that have one,
// everything else here is a direct link.
//
// Deliberately excludes the 21 repos/crates already represented as a SYSTEMS
// entry (content/systems.ts) - PublicSite.tsx filters those out at render time
// rather than this file hand-maintaining two overlapping lists.
//
// Snapshot pulled via `gh repo list <org|user> --json name,isPrivate,url` on
// 2026-08-14 (repos) and the crates.io API on 2026-08-15 (crates) - only public
// repos are listed (a linked private repo 404s for a visitor who isn't a
// collaborator). Will drift as repos/crates are added - re-pull periodically.
export const RFI_REPOS: { n: string; u: string }[] = [
  { n: '.github', u: 'https://github.com/rfi-irfos/.github' },
  { n: '13', u: 'https://github.com/rfi-irfos/13' },
  { n: 'auto-bayesian', u: 'https://github.com/rfi-irfos/auto-bayesian' },
  { n: 'autoguardrails', u: 'https://github.com/rfi-irfos/autoguardrails' },
  { n: 'causal-perception-implementation', u: 'https://github.com/rfi-irfos/causal-perception-implementation' },
  { n: 'e-techbike-at', u: 'https://github.com/rfi-irfos/e-techbike-at' },
  { n: 'gen-fraud-graph', u: 'https://github.com/rfi-irfos/gen-fraud-graph' },
  { n: 'genesis', u: 'https://github.com/rfi-irfos/genesis' },
  { n: 'genetic-algorithm', u: 'https://github.com/rfi-irfos/genetic-algorithm' },
  { n: 'linear-adapter-trainer', u: 'https://github.com/rfi-irfos/linear-adapter-trainer' },
  { n: 'llm_bridge', u: 'https://github.com/rfi-irfos/llm_bridge' },
  { n: 'mech-gov-framework', u: 'https://github.com/rfi-irfos/mech-gov-framework' },
  { n: 'mutatis-mutandis', u: 'https://github.com/rfi-irfos/mutatis-mutandis' },
  { n: 'nikoletta-tutor', u: 'https://github.com/rfi-irfos/nikoletta-tutor' },
  { n: 'ntpsec', u: 'https://github.com/rfi-irfos/ntpsec' },
  { n: 'p2p-repository', u: 'https://github.com/rfi-irfos/p2p-repository' },
  { n: 'ralph', u: 'https://github.com/rfi-irfos/ralph' },
  { n: 'ralph-vault-skill', u: 'https://github.com/rfi-irfos/ralph-vault-skill' },
  { n: 'rfi-irfos-web', u: 'https://github.com/rfi-irfos/rfi-irfos-web' },
  { n: 'RuVector', u: 'https://github.com/rfi-irfos/RuVector' },
  { n: 'sota-stressed-datasets', u: 'https://github.com/rfi-irfos/sota-stressed-datasets' },
  { n: 'ternary-intelligence-stack-genesis-archive', u: 'https://github.com/rfi-irfos/ternary-intelligence-stack-genesis-archive' },
]

export const SIMEON_REPOS: { n: string; u: string }[] = [
  { n: 'abliterator', u: 'https://github.com/simeon-kepp/abliterator' },
  { n: 'albert-strategy-orchestrator', u: 'https://github.com/simeon-kepp/albert-strategy-orchestrator' },
  { n: 'ansible', u: 'https://github.com/simeon-kepp/ansible' },
  { n: 'api-guidelines', u: 'https://github.com/simeon-kepp/api-guidelines' },
  { n: 'api-registry', u: 'https://github.com/simeon-kepp/api-registry' },
  { n: 'awesome-go', u: 'https://github.com/simeon-kepp/awesome-go' },
  { n: 'awesome-iOS-security-tools', u: 'https://github.com/simeon-kepp/awesome-iOS-security-tools' },
  { n: 'awesome-mac', u: 'https://github.com/simeon-kepp/awesome-mac' },
  { n: 'awesome-python', u: 'https://github.com/simeon-kepp/awesome-python' },
  { n: 'awesome-scalability', u: 'https://github.com/simeon-kepp/awesome-scalability' },
  { n: 'bazaarak', u: 'https://github.com/simeon-kepp/bazaarak' },
  { n: 'burn', u: 'https://github.com/simeon-kepp/burn' },
  { n: 'candle', u: 'https://github.com/simeon-kepp/candle' },
  { n: 'committers.top', u: 'https://github.com/simeon-kepp/committers.top' },
  { n: 'crewAI', u: 'https://github.com/simeon-kepp/crewAI' },
  { n: 'cybersecurity-SOAR', u: 'https://github.com/simeon-kepp/cybersecurity-SOAR' },
  { n: 'deutsch-lernen-pwa', u: 'https://github.com/simeon-kepp/deutsch-lernen-pwa' },
  { n: 'dynamodb-toolbox', u: 'https://github.com/simeon-kepp/dynamodb-toolbox' },
  { n: 'flax', u: 'https://github.com/simeon-kepp/flax' },
  { n: 'foodsharing', u: 'https://github.com/simeon-kepp/foodsharing' },
  { n: 'frida-ipa-extract', u: 'https://github.com/simeon-kepp/frida-ipa-extract' },
  { n: 'frida-tools', u: 'https://github.com/simeon-kepp/frida-tools' },
  { n: 'github-mcp-server', u: 'https://github.com/simeon-kepp/github-mcp-server' },
  { n: 'hermes-agent', u: 'https://github.com/simeon-kepp/hermes-agent' },
  { n: 'hermes-agent-bundle', u: 'https://github.com/simeon-kepp/hermes-agent-bundle' },
  { n: 'hermes-bundle', u: 'https://github.com/simeon-kepp/hermes-bundle' },
  { n: 'hermes-setup', u: 'https://github.com/simeon-kepp/hermes-setup' },
  { n: 'iOS-Binary-Security-Analyzer', u: 'https://github.com/simeon-kepp/iOS-Binary-Security-Analyzer' },
  { n: 'jadx', u: 'https://github.com/simeon-kepp/jadx' },
  { n: 'jupyterlab_pygments', u: 'https://github.com/simeon-kepp/jupyterlab_pygments' },
  { n: 'keras', u: 'https://github.com/simeon-kepp/keras' },
  { n: 'linguist', u: 'https://github.com/simeon-kepp/linguist' },
  { n: 'llama.cpp', u: 'https://github.com/simeon-kepp/llama.cpp' },
  { n: 'lunar-phase-calendar', u: 'https://github.com/simeon-kepp/lunar-phase-calendar' },
  { n: 'MixedRadixCircuitSynthesis', u: 'https://github.com/simeon-kepp/MixedRadixCircuitSynthesis' },
  { n: 'ML-From-Scratch', u: 'https://github.com/simeon-kepp/ML-From-Scratch' },
  { n: 'netron', u: 'https://github.com/simeon-kepp/netron' },
  { n: 'OntologyScope', u: 'https://github.com/simeon-kepp/OntologyScope' },
  { n: 'openapi-to-graphql', u: 'https://github.com/simeon-kepp/openapi-to-graphql' },
  { n: 'osiris', u: 'https://github.com/simeon-kepp/osiris' },
  { n: 'pocketbase', u: 'https://github.com/simeon-kepp/pocketbase' },
  { n: 'PowerToys', u: 'https://github.com/simeon-kepp/PowerToys' },
  { n: 'python-ternary', u: 'https://github.com/simeon-kepp/python-ternary' },
  { n: 'ResonanceFlow', u: 'https://github.com/simeon-kepp/ResonanceFlow' },
  { n: 'rfi-labs-arcade', u: 'https://github.com/simeon-kepp/rfi-labs-arcade' },
  { n: 'ruflo', u: 'https://github.com/simeon-kepp/ruflo' },
  { n: 'RuVector', u: 'https://github.com/simeon-kepp/RuVector' },
  { n: 'RuView', u: 'https://github.com/simeon-kepp/RuView' },
  { n: 'rvllm', u: 'https://github.com/simeon-kepp/rvllm' },
  { n: 'simeon-kepp', u: 'https://github.com/simeon-kepp/simeon-kepp' },
  { n: 'SoftwareSystemsEngineering', u: 'https://github.com/simeon-kepp/SoftwareSystemsEngineering' },
  { n: 'sparc', u: 'https://github.com/simeon-kepp/sparc' },
  { n: 'Synaptic-Mesh', u: 'https://github.com/simeon-kepp/Synaptic-Mesh' },
  { n: 'tensorflow', u: 'https://github.com/simeon-kepp/tensorflow' },
  { n: 'tensorzero', u: 'https://github.com/simeon-kepp/tensorzero' },
  { n: 'Termix', u: 'https://github.com/simeon-kepp/Termix' },
  { n: 'TernaryMoralLogic', u: 'https://github.com/simeon-kepp/TernaryMoralLogic' },
  { n: 'TernCore-Silicon', u: 'https://github.com/simeon-kepp/TernCore-Silicon' },
  { n: 'TernVector', u: 'https://github.com/simeon-kepp/TernVector' },
  { n: 'the-book-of-secret-knowledge', u: 'https://github.com/simeon-kepp/the-book-of-secret-knowledge' },
  { n: 'tinygrad', u: 'https://github.com/simeon-kepp/tinygrad' },
  { n: 'top-github-users', u: 'https://github.com/simeon-kepp/top-github-users' },
  { n: 'wayfinder', u: 'https://github.com/simeon-kepp/wayfinder' },
  { n: 'xlstm', u: 'https://github.com/simeon-kepp/xlstm' },
]

// All 47 published crates.io packages (live-verified 2026-08-15) - the 12 with
// glosses in a SYSTEMS entry are excluded here (rendered via the modal instead).
export const CRATES: { n: string; u: string }[] = [
  { n: 'ternlang-ml', u: 'https://crates.io/crates/ternlang-ml' },
  { n: 'ternlang-runtime', u: 'https://crates.io/crates/ternlang-runtime' },
  { n: 'ternlang-hdl', u: 'https://crates.io/crates/ternlang-hdl' },
  { n: 'moe-llb', u: 'https://crates.io/crates/moe-llb' },
  { n: 'ternlang-cli', u: 'https://crates.io/crates/ternlang-cli' },
  { n: 'ternlang-lsp', u: 'https://crates.io/crates/ternlang-lsp' },
  { n: 'ternlang-mcp', u: 'https://crates.io/crates/ternlang-mcp' },
  { n: 'moe-platform', u: 'https://crates.io/crates/moe-platform' },
  { n: 'ternlang-compat', u: 'https://crates.io/crates/ternlang-compat' },
  { n: 'moe-plugin-sdk', u: 'https://crates.io/crates/moe-plugin-sdk' },
  { n: 'ternpkg', u: 'https://crates.io/crates/ternpkg' },
  { n: 'ternlang-codegen', u: 'https://crates.io/crates/ternlang-codegen' },
  { n: 'ternlang-test', u: 'https://crates.io/crates/ternlang-test' },
  { n: 'ternlang-compress', u: 'https://crates.io/crates/ternlang-compress' },
  { n: 'moe-runtime', u: 'https://crates.io/crates/moe-runtime' },
  { n: 'moe-reference', u: 'https://crates.io/crates/moe-reference' },
  { n: 'moe-ddel', u: 'https://crates.io/crates/moe-ddel' },
  { n: 'moe-sdk', u: 'https://crates.io/crates/moe-sdk' },
  { n: 'pytern', u: 'https://crates.io/crates/pytern' },
  { n: 'ternaudit-guard', u: 'https://crates.io/crates/ternaudit-guard' },
  { n: 'moe-llm-core', u: 'https://crates.io/crates/moe-llm-core' },
  { n: 'moe-compute', u: 'https://crates.io/crates/moe-compute' },
  { n: 'moe-uril', u: 'https://crates.io/crates/moe-uril' },
  { n: 'moe-validation-suite', u: 'https://crates.io/crates/moe-validation-suite' },
  { n: 'albert-reference', u: 'https://crates.io/crates/albert-reference' },
  { n: 'lauras-team', u: 'https://crates.io/crates/lauras-team' },
  { n: 'call-laura-core', u: 'https://crates.io/crates/call-laura-core' },
  { n: 'moe-test', u: 'https://crates.io/crates/moe-test' },
  { n: 'ternary-core', u: 'https://crates.io/crates/ternary-core' },
  { n: 'lauras-mcp', u: 'https://crates.io/crates/lauras-mcp' },
  { n: 'ternlang-api', u: 'https://crates.io/crates/ternlang-api' },
  { n: 'lauras-api', u: 'https://crates.io/crates/lauras-api' },
  { n: 'laura-mcp', u: 'https://crates.io/crates/laura-mcp' },
  { n: 'albert-compat', u: 'https://crates.io/crates/albert-compat' },
  { n: 'albert-tools', u: 'https://crates.io/crates/albert-tools' },
  { n: 'albert-commands', u: 'https://crates.io/crates/albert-commands' },
]
export const CRATES_IO_PROFILE = 'https://crates.io/users/simeon-kepp'
